### ISSUE TITLE
Cannot make it work

### ISSUE THREAD

**Issue by ecerroni** [mauricius/vue-draggable-resizable#1]
After installing the package I'm getting this error

```
 ERROR  Failed to compile with 2 errors                                                                                                 11:03:17 AM

This dependency was not found:

* vue-draggable-resizable in ./src/main.js, ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/Home.vue

To install it, you can run: npm install --save vue-draggable-resizable
```
![draggable-dependency](https://user-images.githubusercontent.com/11174327/27074683-1dc25852-5028-11e7-8a57-a9b361234acd.png)

The package name is present in package.json (`"vue-draggable-resizable": "1.0.0",`) as well as stored under node_modules

Vue version is `2.3.3`
Node evrsion `v6.1.0`

It seems there is no `dist` folder:
![no_dist](https://user-images.githubusercontent.com/11174327/27075215-c3ade550-5029-11e7-9a7d-391cfe00302c.png)

**Comment by mauricius** [comment]
Sorry @ecerroni I missed the `.npmignore` file, so the package did not get fully published on npm. You can try now with version 1.0.1.

**Comment by ecerroni** [comment]
Now it works :) Thanks!
