### ISSUE TITLE
About element alignment

### ISSUE THREAD

**Issue by gorkys** [mauricius/vue-draggable-resizable#109]
Are you considering adding element alignment? Like Snap to element or grid in Jquery UI draggable.(https://jqueryui.com/resources/demos/draggable/snap-to.html)

**Comment by mauricius** [comment]
Snapping to grid is already available on the main branch (a little buggy, but working) and also on the the new version 2.

On the other hand, snapping to other components has been already discussed in #18 and, even a year later, I did not change my mind about it. It's something that traspass the boundaries of the component.

**Comment by gorkys** [comment]
@mauricius Like jQueryUI https://jqueryui.com/draggable/#snap-to，Is there any good idea to implement this feature?If it is possible，please tell me。thank you！

**Comment by mauricius** [comment]
No, I really don't think that is a good idea.
