### ISSUE TITLE
Infinite resize

### ISSUE THREAD

**Issue by Romick2005** [mauricius/vue-draggable-resizable#111]
Hi mauricios,

Found curios bug and want to share it with you:

Steps to reproduce:
0) Add "resizestop" handler.
1) Activate component pragmatically (set active = true). PS. Please do this without any clickable activation. (Do not click on component before for activating it).
2) Check results for "resizestop" handler.

Investigation results: 
 - handleUp handler is never called because it added in elementDown but not in handleDown.
- It is develop branch (version 2).

Thank for great component!
Romick

**Comment by mauricius** [comment]
Thanks, I'll look into it.
