### ISSUE TITLE
Setting draggable to false appends the popup to the end of the page

### ISSUE THREAD

**Issue by dmrickey** [mauricius/vue-draggable-resizable#112]
I'm trying to toggle draggable (so something like `:draggable="shouldDrag"`based on some criteria, but whenever I set it to false, my view gets appended to the end of the page instead of staying in place.  

Should I be able to toggle draggable like this to lock the view in place where it currently is?

**Comment by mauricius** [comment]
Which version are you currently using? Master (v1) or dev (v2)? Also can you provide an example of your code or a link to reproduce the issue?

**Comment by TitanFighter** [comment]
@dmrickey 
Here is the example of v1 where you can click a button to disable dragging and you will see that nothing `gets appended to the end of the page`.
[Demo](https://codesandbox.io/s/0pjjwolqrl)

**Comment by dmrickey** [comment]
Sorry for the slooow response.  We're using 1.5.0.  At this point I don't even remember what I was working on and since it has been proven to work otherwise, I'll just close this and worry about it later after we've updated if it's still a problem.
