### ISSUE TITLE
Constrain Width and Height to perfect square?

### ISSUE THREAD

**Issue by NeoMarine** [mauricius/vue-draggable-resizable#116]
Hello, is it possible to have it so that, e.g. if a user is holding down "CTRL" key, when resizing it constraints the width/height to match each other? I've attempted this myself but can't seem to work out how.

**Comment by TitanFighter** [comment]
There is no such thing from the box right now, AFAIK, and I think it could be possible to do implement it from your side, but just in case if `props` was reactive. In the current master version they are not reactive, so you can try to implement this feature using dev branch.

**Comment by NeoMarine** [comment]
Any chance you could give an example code? Really can't figure it out. But then again it would be better just to update the main git with this feature anyway.

**Comment by TitanFighter** [comment]
I did not have such task, so I can not provide any code for now, but idea is to ... :
1. [Take this branch](https://github.com/mauricius/vue-draggable-resizable/tree/develop)
2. Look at [System Modifier Keys](https://vuejs.org/v2/guide/events.html#System-Modifier-Keys)
3. Implement a method with the next logic: when ctrl+click+drag happens, [change `:width` or `:height`](https://github.com/mauricius/vue-draggable-resizable/tree/develop#install-and-basic-usage) of vue-draggable-resizable as you need.

If have any problem, feel free to post.

**Comment by janvorisek** [comment]
I have implemented this feature using the `:lock-aspect-ratio` prop without the need of CTRL. I tried to use the resizing event at first, but that didn't work. My solution is to use mouseover event on the parent element and lock the aspect ratio while using the corner handles (top left, top right, bottom left, bottom right). 

Data:
```
data() {
    return {
        constantMode: false
    }
};
```

Template:
```
<template>
  <div
    @mouseover="onResizeStartCallback"
  >
    <vue-draggable-resizable
      :lock-aspect-ratio="constantMode"
    />
  </div>
</template>
```

The callback function
```
onResizeStartCallback(event) {
    const cls = event.target.classList;

    // any non-handle element doesnt change the behaviour 
    if (!cls.contains('handle')) return;

    // i want the corner handles to lock aspect ratio
    const lock = (cls.contains('handle-tl') ||
        cls.contains('handle-tr') ||
        cls.contains('handle-bl') ||
        cls.contains('handle-br')
    );

    this.selection.constantMode = lock;
}
```
