### ISSUE TITLE
How can i rewrite handles style?

### ISSUE THREAD

**Issue by purplepeng** [mauricius/vue-draggable-resizable#118]
Hi, can i rewrite handles style?  I want rewrite style of ".handle", for example use a photo, but i it doesn't work.

**Comment by TitanFighter** [comment]
Look [this](https://github.com/mauricius/vue-draggable-resizable/issues/40)

**Comment by purplepeng** [comment]
Thanks, it works. @TitanFighter

**Comment by mauricius** [comment]
@purplepeng you can also try to use the [dev branch](https://github.com/mauricius/vue-draggable-resizable/tree/develop), which is [style agnostic](https://github.com/mauricius/vue-draggable-resizable/tree/develop#styling).

**Comment by purplepeng** [comment]
Hi, I try with `npm install --save vue-draggable-resizable`, but it didn't contain `vue-draggable-resizable.css` in src folder. @mauricius

**Comment by TitanFighter** [comment]
@purplepeng because by using npm command which you provided you are installing current `master branch` version, instead of `dev branch. Use `npm install https://github.com/mauricius/vue-draggable-resizable#develop`

**Comment by purplepeng** [comment]
I got it, thanks. @TitanFighter
