### ISSUE TITLE
Using 3rd party component I can not sort items inside draggable

### ISSUE THREAD

**Issue by TitanFighter** [mauricius/vue-draggable-resizable#119]
I use [`vue-smooth-dnd`](https://github.com/kutlugsahin/vue-smooth-dnd) as a sortable component inside `vue-draggable-resizeble`.

If I do not apply `dragCancel` to the element with sortable items, `vue-smooth-dnd` does not work (items sorting actually drags `vue-draggable-resizable`).

When I add `dragCancel` class, dragging does not work (as expected), but sorting also does not work.

[Demo](https://codesandbox.io/s/3y6nkkyoyq)
`vue-draggable-resizable` version: 1.7.2

**Comment by TitanFighter** [comment]
@mauricius Thank you very much for the quick fix.

As I did not know when you can fix it, I started to check others sortable libraries as well as `vue-draggable-resizable v2` and I found related problem.

I tried [`vuesortable`](https://github.com/SortableJS/Vue.Draggable). In versions 1.7.2 (so even before your fix) and 1.7.3 it works, but in v2 it does not work.

Here is the working [demo](https://codesandbox.io/s/x253ykkyrq) with `vue-draggable-resizable` 1.7.3 and `vuesortable`, but with `vue-draggable-resizable v2` the same code does not work, so the same problem as in the 1st post, ie.:

> If I do not apply dragCancel to the element with sortable items, vue-smooth-dnd does not work (items sorting actually drags vue-draggable-resizable).

> When I add dragCancel class, dragging does not work (as expected), but sorting also does not work.

Unfortunatelly I can not provide demo for v2 - fully imported to codesandbox [dev branch does not work](https://codesandbox.io/s/github/mauricius/vue-draggable-resizable/tree/develop).

Can you please fix this problem also in v2, because I need reactive props? As far as I have tested v2, this is the single problem so far I have found.

Thank you!

**Comment by mauricius** [comment]
Finally I had the chance to look into your issue. Based on your demo, it seems that you need to [re-enable native drag functionality](https://github.com/mauricius/vue-draggable-resizable/tree/develop#enablenativedrag), as it is disabled by default by the component. Just use `:enable-native-drag="true"` and it should work.

Let me know if it works for you. Also thank you so much for your tests on v2, hopefully I'm able to release it soon.

**Comment by TitanFighter** [comment]
Hi @mauricius
native-drag works. Thank you.
