### ISSUE TITLE
did you register the component correctly?

### ISSUE THREAD

**Issue by msevensun** [mauricius/vue-draggable-resizable#120]
Unknown custom element: <vue-draggable-resizable> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
![image](https://user-images.githubusercontent.com/20658340/47715036-7f517b00-dc79-11e8-84e0-a31eea7224b7.png)
How to fix it? thank you！

**Comment by TitanFighter** [comment]
@msevensun Show how you registered the component. Double check [Install and basic usage](https://github.com/mauricius/vue-draggable-resizable#install-and-basic-usage).
