### ISSUE TITLE
when I add a 'draggable item' to the draggable list;  The new item couldn't drag;

### ISSUE THREAD

**Issue by tingshuai** [mauricius/vue-draggable-resizable#122]
as title;  chinese:( 当我增加一个可拖拽项目，视图更新后新增加的项目不能拖拽 )

**Comment by tingshuai** [comment]
![ezgif-5-8ea070db8aca](https://user-images.githubusercontent.com/23158246/48471402-cc634e80-e82e-11e8-80c9-76aed5e5ebca.gif)

**Comment by gorkys** [comment]
这个应该是你使用时代码问题。只提供动图不提供代码是不友好的。

**Comment by mauricius** [comment]
That is probably a problem on your end. The fact that you're using drag&drop to add components may suggest that click events are hijacked, but I should definitely look at the code to the code to understand what's wrong.

**Comment by tingshuai** [comment]
thank's all of your attention. that's the url of this product.----[https://github.com/tingshuai/BusinessCenter](url)

**Comment by mauricius** [comment]
You are injecting the coordinates in each VDR instance using this code
```
:x="Number(item.style.left)" :y="Number(item.style.top)"
```
but casting something like `100px` to a `Number` results in `NaN`. Use explicit numbers for that purpose.
