### ISSUE TITLE
default display:none;  when change display:block;      Its  width:0 height:0;

### ISSUE THREAD

**Issue by caibinghong** [mauricius/vue-draggable-resizable#124]
`<template>
  <div style="height: 500px; width: 500px; border: 1px solid red; position: relative;" :class="[isShow?'aa':'bb']">
    <vue-draggable-resizable :w="100" :h="100" v-on:dragging="onDrag" v-on:resizing="onResize" :parent="true">
      <p>Hello! I'm a flexible component. You can drag me around and you can resize me.<br>
      X: {{ x }} / Y: {{ y }} - Width: {{ width }} / Height: {{ height }}</p>
    </vue-draggable-resizable>
  </div>
</template>

<script>
import VueDraggableResizable from 'vue-draggable-resizable'

export default {
  data: function () {
    return {
      width: 0,
      height: 0,
      x: 0,
      y: 0
    }
  },
created(){
this.isShow = true;
},
  methods: {
    onResize: function (x, y, width, height) {
      this.x = x
      this.y = y
      this.width = width
      this.height = height
    },
    onDrag: function (x, y) {
      this.x = x
      this.y = y
    }
  }
}
</script>

<style>
  .aa{
    display:block;
  }
  .bb{
    display:none;
  }
</style>`

**Comment by caibinghong** [comment]
at methods，the reviewDimensions  need ;
if(this.isHide(this.$el)){return};



    isHide(obj) {
      var ret = obj.style.display === "none" || (obj.currentStyle && obj.currentStyle === "none") || (window.getComputedStyle && window.getComputedStyle(obj, null).display === "none");             
      if(ret||obj.tagName.toLocaleLowerCase()=="body"){
        return ret
      }else{
         return this.isHide(obj.parentElement);
      }
    }

**Comment by mauricius** [comment]
I don't understand what is your problem. Can you please provide more details to your issue?
