### ISSUE TITLE
Use with nuxt

### ISSUE THREAD

**Issue by nicothin** [mauricius/vue-draggable-resizable#125]
I install this package and:

```vue
<template>
  <no-ssr>
    <div style="height: 500px; width: 500px; border: 1px solid red; position: relative;">
      <vue-draggable-resizable :w="100" :h="100" v-on:dragging="onDrag" v-on:resizing="onResize" :parent="true">
        <p>Hello! I'm a flexible component. You can drag me around and you can resize me.<br>
        X: {{ x }} / Y: {{ y }} - Width: {{ width }} / Height: {{ height }}</p>
      </vue-draggable-resizable>
    </div>
  </no-ssr>
</template>

<script>
import VueDraggableResizable from 'vue-draggable-resizable'

export default {
  components: {
    VueDraggableResizable,
  },
  data () {
    return {
      width: 0,
      height: 0,
      x: 0,
      y: 0,
    }
  },
  methods: {
    onResize: function (x, y, width, height) {
      this.x = x
      this.y = y
      this.width = width
      this.height = height
    },
    onDrag: function (x, y) {
      this.x = x
      this.y = y
    },
  },
}
</script>
```

First reload of my page:
![image](https://user-images.githubusercontent.com/3499680/48707345-381f3000-ec10-11e8-984c-c860dee5657b.png)

Second reload:
![image](https://user-images.githubusercontent.com/3499680/48707413-6b61bf00-ec10-11e8-8db6-cc6a204f2197.png)

**How can i use this package with [nuxt](https://nuxtjs.org/)**? Tell me please.

**Comment by mauricius** [comment]
I'm not an expert on Nuxt, but it's clear that if you try to render the component server-side it will not work because it uses the `document` variable which is defined only inside a browser environment.

I really don't know if you can use the library with Nuxt, but you can try to follow [this suggestion](https://nuxtjs.org/faq/window-document-undefined/) and let me know.

**Comment by askhat** [comment]
@nicothin Nuxt provides an ability to plug in JS code that specifically relies on browser runtime with [plugins](https://nuxtjs.org/guide/plugins/).

Shortly, you have to create a file inside the `plugins` directory, and call it for example `vue-draggable-resizable.js`. Then you need to populate it with imports and using:

```
import Vue from 'vue'
import VueDraggableResizeable from 'vue-draggable-resizeble'

Vue.use(VueDraggableResizeable)
```

After file is made, all you have to is register plugin, you also have an option to forbid SSR for this plugin. Inside `nuxt.config.js`:

```
plugins: [{ src: '@plugins/vue-draggable-resizable', ssr: false }]
```
 
This is it, just make sure you do not use plugin in server side stages of component lifecycle.

**Comment by mauricius** [comment]
Thanks @askhat for the detailed instructions. I hope to try Nuxt sometime in the future.

**Comment by nicothin** [comment]
alas i still need help
I still see an error
```
ReferenceError: document is not defined
    at o (/mnt/d/projects/nuxt-test/node_modules/vue-draggable-resizable/dist/index.js:1:28940)
    at i (/mnt/d/projects/nuxt-test/node_modules/vue-draggable-resizable/dist/index.js:1:28771)
    at t.exports (/mnt/d/projects/nuxt-test/node_modules/vue-draggable-resizable/dist/index.js:1:30393)
   ...
```
I corrected typos made by @askhat (`resiz[ea]ble`), but it still doesn’t work :(
https://github.com/nicothin/nuxt-test/tree/vue-draggable-resizeble — project status with this error

**Comment by askhat** [comment]
@nicothin make sure you disposed `.nuxt` directory just to make sure it is completely fresh build, it might help.

If it won't I could only suggest usning `<no-ssr/>` component which is shipped with Nuxt.

**Comment by askhat** [comment]
@nicothin I've noticed following line

```
import VueDraggableResizable from 'vue-draggable-resizable'
```

And I'd like to ask @mauricius to be so kind to clarify, does the plugin needs to be imported, if it already been used with `Vue.use(require('vue-draggable-resizable'))`.

I suspect yet another implicit import of the code may happen on earlier stages of compilation and cause such errors.

**Comment by nicothin** [comment]
@askhat I deleted the folder `.nuxt` and restarted the server but it still doesn’t work

**Comment by askhat** [comment]
@nicothin try to remove this line

```
import VueDraggableResizable from 'vue-draggable-resizable'
```

and this

```
  components: {
    VueDraggableResizable,
  },
```

**Comment by nicothin** [comment]
@askhat 
I do not have
```
components: {
  VueDraggableResizable,
},
```
if i remove `import VueDraggableResizable from 'vue-draggable-resizable'`, i get an error: 
```
NuxtServerError
render function or template not defined in component: anonymous
```

**Comment by nicothin** [comment]
@mauricius reopen this issue please.
The problem has not been solved yet.

**Comment by askhat** [comment]
I'd suggest to open another with request to make a Nuxt plugin. If I'll have enough spare time, I even willing to write it myself.

**Comment by mauricius** [comment]
Sorry for the delay @nicothin. I made a [PR](https://github.com/nicothin/nuxt-test/pull/1) to your repository fixing what I thought to be the problem. Check it out and let me know.

>And I'd like to ask @mauricius to be so kind to clarify, does the plugin needs to be imported, if it already been used with Vue.use(require('vue-draggable-resizable')).

@askhat actually this is not a plugin, but a component. Therefore it needs to be registered inside Vue by using the `Vue.component('my-component-name', { ... })` notation.

**Comment by nicothin** [comment]
@mauricius thank you so much!

**Comment by nicothin** [comment]
A little worried that updating the page causes an error.
And generating static pages does not work. :(
`ReferenceError: document is not defined`

**Comment by mauricius** [comment]
@nicothin try with this one https://github.com/nicothin/nuxt-test/pull/2

**Comment by nicothin** [comment]
@mauricius thank you!
it works!
