### ISSUE TITLE
Change width, height, x, and y by input form

### ISSUE THREAD

**Issue by caturseptian** [mauricius/vue-draggable-resizable#126]
with multiple component, how to change width, height, x, and y by input form?
because the component only changes when resized

1. 
![image](https://user-images.githubusercontent.com/13551379/48883712-a7d12d00-ee53-11e8-9b83-bf42fc2ab31c.png)

2. 
![image](https://user-images.githubusercontent.com/13551379/48883749-d222ea80-ee53-11e8-8212-a8c93bdb88e5.png)
![image](https://user-images.githubusercontent.com/13551379/48883768-eebf2280-ee53-11e8-96a2-57854b183082.png)

**Comment by TitanFighter** [comment]
Use v2 version in dev branch. v1 does not support reactive props.

**Comment by caturseptian** [comment]
> Use v2 from dev branch. v1 does not support reactive props.

I've used v2

**Comment by TitanFighter** [comment]
Show your code

**Comment by caturseptian** [comment]
> Show your code

https://jsfiddle.net/ccseptian/eywraw8t/473382/

`<div id="app">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card mb-3">
          <div class="card-body">
            <button type="button" class="btn btn-primary" @click="addElement">
              Add Element
            </button>
          </div>
        </div>
        
        <div class="card mb-3" v-show="active">
          <div class="card-body">
            <form>
              <div class="form-group">
                <label>Size & Position</label>
                <div class="row mb-3">
                  <div class="col d-flex justify-content-between">
                    <label for="width" class="col-form-label col-form-label-sm mr-sm-2" style="min-width: 14px !important;">W</label>
                    <div class="input-group input-group-sm">
                      <input type="number" name="width" id="width" class="form-control"
                             @change="changeElement"
                             v-model="w">
                      <div class="input-group-append">
                        <span class="input-group-text">px</span>
                      </div>
                    </div>
                  </div>

                  <div class="col d-flex justify-content-between">
                    <label for="x" class="col-form-label col-form-label-sm mr-sm-2"
                           style="min-width: 14px !important;">X</label>
                    <div class="input-group input-group-sm">
                      <input type="number" name="x" id="x" class="form-control"
                             @change="changeElement"
                             v-model="x">
                      <div class="input-group-append">
                        <span class="input-group-text">px</span>
                      </div>
                    </div>
                  </div>
                </div>

                <div class="row">
                  <div class="col d-flex justify-content-between">
                    <label for="height" class="col-form-label col-form-label-sm mr-sm-2" style="min-width: 14px !important;">H</label>
                    <div class="input-group input-group-sm">
                      <input type="number" name="height" id="height" class="form-control"
                             @change="changeElement"
                             v-model="h">
                      <div class="input-group-append">
                        <span class="input-group-text">px</span>
                      </div>
                    </div>
                  </div>

                  <div class="col d-flex justify-content-between">
                    <label for="y" class="col-form-label col-form-label-sm mr-sm-2"
                           style="min-width: 14px !important;">Y</label>
                    <div class="input-group input-group-sm">
                      <input type="number" name="y" id="y" class="form-control"
                             @change="changeElement"
                             v-model="y">
                      <div class="input-group-append">
                        <span class="input-group-text">px</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
      
      <div class="col-md-6">
        <div class="card">
          <div class="card-body">
            <div style="width: 400px; height: 600px; position: relative; background-color: wheat;">
              <template v-for="(element, index) in elements">
                <vue-draggable-resizable
                                         style="background-color: #332c2b;"
                                         :parent="true" :resizable="true"
                                         :x="element.x" :y="element.y"
                                         :w="element.w" :h="element.h"
                                         style="border: 1px solid"
                                         @activated="onActivate(element, index)" @deactivated="onDeactivate(element, index)"
                                         @resizing="onResize"
                                         @dragging="onDrag">
                </vue-draggable-resizable>
              </template>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
`

`const app = new Vue({
  el: "#app",
  data: {
    active: null,
    elements: [
      {
      	active: false,
      	w: 50,
        h: 50,
        x: 10,
        y: 10
      }
    ],
    w: null,
    h: null,
    x: null,
    y: null,
    index: null
  },
  methods: {
  	addElement: function () {
      this.active = false;
      this.elements.push({
        active: true,
        w: 300,
        h: 100,
        x: 50,
        y: 200,
      });
    },
    onActivate: function (element, index) {
      element.active = true;
      this.active = element.active;
      this.w = element.w;
      this.h = element.h;
      this.x = element.x;
      this.y = element.y;

      this.index = index;
    },
    onDeactivate: function (element, index) {
      element.active = false;
      this.index = index;
    },
    onResize: function (x, y, width, height) {
      this.x = x;
      this.y = y;
      this.width = width;
      this.height = height;
      this.w = this.width;
      this.h = this.height;
    },
    onDrag: function (x, y) {
      this.x = x;
      this.y = y;
    },
    changeElement: function () {
      app.elements[app.index]['w'] = Number(app.w);
      app.elements[app.index]['h'] = Number(app.h);
      app.elements[app.index]['x'] = Number(app.x);
      app.elements[app.index]['y'] = Number(app.y);
    }
  }
})`

**Comment by TitanFighter** [comment]
You have multiple issues with the provided code:
```
<template v-for="(element, index) in elements">
    <vue-draggable-resizable
                                style="background-color: #332c2b;"
                                :parent="true" :resizable="true"
                                :x="element.x" :y="element.y"
                                :w="element.w" :h="element.h"
                                style="border: 1px solid"
                                @activated="onActivate(element, index)" @deactivated="onDeactivate(element, index)"
                                @resizing="onResize"
                                @dragging="onDrag">
    </vue-draggable-resizable>
</template>
```
1. `v-for` can be used with `<template>`. Use for example `<div>`.
2. `v-for` requires `:key`, so use (probably) `index` -> `<template v-for="(element, index) in elements" :key="index">`
3. You use `style` twice -> combine them -> `style="background-color: #332c2b; border: 1px solid"

Fixed [demo](https://codesandbox.io/s/50rk848z4p)
____

Your demo is based on v1.7.4. Again, for your task you need to use [v2 version from dev branch](https://github.com/mauricius/vue-draggable-resizable/tree/develop).
You can install it into your project using `npm install https://github.com/mauricius/vue-draggable-resizable#develop --save`

Then in your `main.js`:
```
import VueDraggableResizable from 'vue-draggable-resizable/src/index'
import 'vue-draggable-resizable/src/components/vue-draggable-resizable.css'
Vue.component('vue-draggable-resizable', VueDraggableResizable)
```
____

If still can not make it work, ping me here.

**Comment by caturseptian** [comment]
> @caturseptian
> 
> You have 3 issues with the provided code:
> 
> ```
> <template v-for="(element, index) in elements">
>     <vue-draggable-resizable
>                                 style="background-color: #332c2b;"
>                                 :parent="true" :resizable="true"
>                                 :x="element.x" :y="element.y"
>                                 :w="element.w" :h="element.h"
>                                 style="border: 1px solid"
>                                 @activated="onActivate(element, index)" @deactivated="onDeactivate(element, index)"
>                                 @resizing="onResize"
>                                 @dragging="onDrag">
>     </vue-draggable-resizable>
> </template>
> ```
> 1. `v-for` can not be used with `<template>`. Use for example `<div>`.
> 2. `v-for` requires `:key`, so use (probably) `index` -> `<template v-for="(element, index) in elements" :key="index">`
> 3. You use `style` twice -> combine them -> `style="background-color: #332c2b; border: 1px solid"
> 
> Fixed [demo](https://codesandbox.io/s/50rk848z4p)
> 
> Your demo is based on v1.7.4. Again, for your task you need to use [v2 version from dev branch](https://github.com/mauricius/vue-draggable-resizable/tree/develop).
> You can install it into your project using `npm install https://github.com/mauricius/vue-draggable-resizable#develop --save`
> 
> Then in your `main.js`:
> 
> ```
> import VueDraggableResizable from 'vue-draggable-resizable/src/index'
> import 'vue-draggable-resizable/src/components/vue-draggable-resizable.css'
> Vue.component('vue-draggable-resizable', VueDraggableResizable)
> ```
> If still can not make it work, ping me here.

resize work, but element is always above, 
"y" cannot be set

![image](https://user-images.githubusercontent.com/13551379/48990238-3bf70900-f160-11e8-961f-e43da8ff98bb.png)

**Comment by caturseptian** [comment]
@TitanFighter 
![image](https://user-images.githubusercontent.com/13551379/48990621-b411fe80-f161-11e8-96de-47ebe899a5c8.png)
![image](https://user-images.githubusercontent.com/13551379/48990639-c5f3a180-f161-11e8-8f25-3420a15a1854.png)

**Comment by TitanFighter** [comment]
Regarding `but element is always above` -> remove one div and put `v-for` and `:key` one level below:
```
    <div style="width: 400px; height: 600px; position: relative; background-color: wheat;">
       <!-- <div v-for="(element, index) in elements" :key="index"> -->
        <vue-draggable-resizable v-for="(element, index) in elements" :key="index"
                                 style="background-color: #332c2b; border: 1px solid"
                                 :parent="true" :resizable="true"
                                 :x="element.x" :y="element.y"
                                 :w="element.w" :h="element.h"
                                 @activated="onActivate(element, index)"
                                 @deactivated="onDeactivate(element, index)"
                                 @resizing="onResize"
                                 @dragging="onDrag">
        </vue-draggable-resizable>
      <!-- </div> -->
    </div>
```
Regarding `"h" & "y" cannot be set`. As I see there is a delay and input focus issue. These issues does not have any relation to `vue-draggable-resizable`. As a workaround you can replace all `@change="changeElement"` in `input` to `@click="changeElement" @keyup.enter="changeElement"`, i.e:
```
<input type="number" name="height" id="height" class="form-control"
     @click="changeElement" @keyup.enter="changeElement"
     v-model="h">
```
