### ISSUE TITLE
Disable dragging/resize

### ISSUE THREAD

**Issue by mkhanal** [mauricius/vue-draggable-resizable#128]
I've got a use case where I do not want users to re-organise the elements on the screen if they don't have the rights. It's like a read-only view. 

It would be nice to be able to have flags like `disableDrag: true/false` to manage this.

**Comment by TitanFighter** [comment]
Set `draggable=false` if user does not have the needed right. I do not remember if `draggable` in v1 support reactivity, so check it yourself. If does not support - use v2 (in dev branch).

**Comment by mkhanal** [comment]
Oo...I totally missed the :draggable=false flag. Thanks for that.
