### ISSUE TITLE
select text inside the div

### ISSUE THREAD

**Issue by PsidomPC** [mauricius/vue-draggable-resizable#129]
I would like to create a draggable and resizable text box using this component; Everything works fine except it doesn't allow me to select text inside the box, that is when I mousedown and move, the behavior is dragging the box, while I would like it to be able to select text inside the box, that is, ignore dragging when mouse is inside the box. Is it possible for me to restrict the drag effect to be applied only when the mousedown is on the edges of the div? Thanks in advance ~

**Comment by TitanFighter** [comment]
Check `Drag Handle and Drag Cancel` at the [bottom](https://mauricius.github.io/vue-draggable-resizable/). Is it suitable?

**Comment by PsidomPC** [comment]
Yep. Just figure out that I can use the dragHandle property. Pretty much what I needed. Though it would be even better to be able to drag when mouse is at the edge of the div ;)

**Comment by TitanFighter** [comment]
@PsidomPC Something like [this](https://codesandbox.io/s/j714n3k3ry)?

**Comment by mauricius** [comment]
>Though it would be even better to be able to drag when mouse is at the edge of the div ;) Or even a dedicated drag handle like the resize handles

This falls into the category of edge cases and what would work for you may not work for others. You can use `dragHandle`, just like @TitanFighter pointed out, which is perfect for such use cases

**Comment by PsidomPC** [comment]
ok @TitanFighter that is a pretty cool solution. I think I'll go with that. thanks
