### ISSUE TITLE
Draggables "pile down" if constructed using v-for

### ISSUE THREAD

**Issue by lmr2391** [mauricius/vue-draggable-resizable#13]
When I want to generate multiple draggables within one parent div using the v-for directive, the domain in which they can move in the y-direction piles up from the space in the y-direction, their predecessors are using.

So for example if the first element constructed using v-for has a size of (100, 100) and the second element is supposed to appear at (0,0), it appears at (0, 100) of the parent component but thinks, it is at (0, 0). As a consequence it can be moved down to y=(600-own height), even if the domain is only supposed to have a size of 500. Interestingly, this piling only occurs in the y-direction but not in the x-direction. I don't know whether the issue becomes clear in my description, so here is some example code.
```
<template>
<div id="app" class="container">
  <div style="height: 500px; width: 500px; border: 1px solid red; position: relative;">
    <template v-for="element in elements">
      <vue-draggable-resizable :parent="true" :resizable="true" :x="element.x" :y="element.y" @dragstop="(x,y) => updateElementPosition(element, x, y)" style="border: 1px solid">
        <p>{{ element.text }}</p>
        <p>x-position: {{ element.x }} y-position: {{ element.y }}</p>
      </vue-draggable-resizable>
    </template>
  </div>
</div>
</template>

<script>
import VueDraggableResizable from 'vue-draggable-resizable'

export default {
  name: 'app',
  components: {
    VueDraggableResizable
  },
  data () {
    return {
      elements: [
        {
          text: 'I can be moved around freely within the parent',
          x: 0,
          y: 0
        },
        {
          text: 'My initial position is set to 0,0 but I appear below the previous element at 0, 200 and can be moved further down than the border of my parent',
          x: 0,
          y: 0
        },
        {
          text: 'I appear below the lower end of my predecessor. If the size of one of them is changed, I move accordingly without changing my coordinates',
          x: 0,
          y: 0
        }
      ]
    }
  },
  methods: {
    updateElementPosition (element, x, y) {
      element.x = x
      element.y = y
    }
  }
}
</script>
```

I'm using vue-draggable-resizable 1.2.2 and Vue 2.3.4

**Comment by lmr2391** [comment]
Wait, this doesn't only happen when using v-for but also when defining multiple v-draggable-resizable's within one parent div. Am I doing something wrong?

**Comment by lmr2391** [comment]
If I change the css property `position` of `.vdr` from `relative` to `absolute` this works as expected. Also it doesn't break any tests. But I don't know about any other implications.

**Comment by mauricius** [comment]
It was obviously a bug, thanks for spotting it.

I also added your example to the documentation.

**Comment by xlcrr** [comment]
I'm having the same problem with 2.3.0

**Comment by Lycon1996** [comment]
Has this problem been solved

**Comment by Lycon1996** [comment]
> 这个问题解决了

OK fine ， just add css 'position：absolute' for vdr
