### ISSUE TITLE
Support for dynamic starting position

### ISSUE THREAD

**Issue by joaossantos** [mauricius/vue-draggable-resizable#130]
Is there a way to initially position the draggable item in the center of an element?

Using css _Flexbox Layout_ or something like `left: 50%; top: 50%;` doesn't seem to work.

What happens:
![display1](https://user-images.githubusercontent.com/45002783/49300080-3fb8c180-f4b9-11e8-81e8-b2285c635ef2.png)

What I need: 
![display2](https://user-images.githubusercontent.com/45002783/49300091-43e4df00-f4b9-11e8-93f9-e720270d05de.png)

**Comment by TitanFighter** [comment]
Possibly duplication #105

**Comment by joaossantos** [comment]
Thank you for the quick response + help, it is now working as intended.
