### ISSUE TITLE
Update component properties at runtime? (reverse of @onResize/@onDrag)

### ISSUE THREAD

**Issue by toddkao** [mauricius/vue-draggable-resizable#131]
I'm able to correctly synchronize data with the resizing/dragging events,
however is there a way to do the reverse?

If I update the data manually, is there a way to update the component's properties ? 

Binding x, y, w, h only sets the default values on mount, I want to be able to edit the data properties (x, y, w, h) through a function and have the component visually update.

**Comment by TitanFighter** [comment]
This is a duplicate of #14.

In short, use v2 from dev branch.
`npm install https://github.com/mauricius/vue-draggable-resizable#develop --save`

Then in your `main.js`:
```
import VueDraggableResizable from 'vue-draggable-resizable/src/index'
import 'vue-draggable-resizable/src/components/vue-draggable-resizable.css'
Vue.component('vue-draggable-resizable', VueDraggableResizable)
```

**Comment by toddkao** [comment]
Thanks
