### ISSUE TITLE
Please release the beta

### ISSUE THREAD

**Issue by tpraxl** [mauricius/vue-draggable-resizable#132]
I'd really like to use vue-draggable-resizable 2.0.0-beta.0 and I would kindly ask you to release the beta to npmjs.com.

This is because I'm experiencing problems when I add the following dependency to use your develop branch 

```json
"vue-draggable-resizable": "git+https://github.com/mauricius/vue-draggable-resizable.git#develop",
```

I get the following error when I serve my application:

```
This dependency was not found:

* vue-draggable-resizable in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/DraggableImage.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save vue-draggable-resizable
```

So I need to `import VueDraggableResizable from 'vue-draggable-resizable/src/index';`

But this file is not transpiled and it seems to miss important steps, when it gets transpiled during my build.

Using it like that causes IE11 to output an error message about a syntax error somewhere in the minified js. However, when I checkout your the develop branch and run the demo with `npm run serve`, it shows that it is compatible to IE11.

I would very much appreciate a beta-release.

**Comment by TitanFighter** [comment]
Hi @mauricius . I do not have any clue about the problem above, since I did not test the component with IE11, so can not help, but regarding releasing of a beta version - could you do it please? :) and later when you have time you finish maxHeight and maxWeight. You can release it, for example, as v2.0.0 rc1 (bootstrap-vue does it in this way).
Thanks :)

**Comment by mauricius** [comment]
Sorry for getting back to you so late.

I don't have Windows so I cannot fully test your problem. Regarding the beta version, my plan is to release it before Christmas, I need to finish `minHeight` and `minWidth` props which are actually implemented, but I still need to figure out how to make them work along with the aspect ratio prop. In the meantime I'm fixing a few bugs here and there. I'm confident that I'll be able to finish this feature in time and release a first release candidate.

**Comment by yangzhixiao** [comment]
I can't wait to use version 2.0 in my project.
Since my project need to use some new features.
Such as mutiple select, mutiple move...
Thanks.
