### ISSUE TITLE
parent element size update

### ISSUE THREAD

**Issue by eyaylagul** [mauricius/vue-draggable-resizable#133]
i wrote a designer for something. I used parent settings true, its worked right. But designer parent have changeable size. If selected bigger or smaller size after mounted, VDR component parent settings works according to mounted parent size. How i can update VDR component parent size?

i use #develop branch for aspect ratio feature

![kapture 2018-12-06 at 11 53 07](https://user-images.githubusercontent.com/5664725/49572774-90af3680-f94d-11e8-8541-c66c7e7e6401.gif)

**Comment by TitanFighter** [comment]
Seems to be a duplicate #91

**Comment by eyaylagul** [comment]
I dont like use settimeout function to like these needs. But now i cant finding solution without  non-dependency. So its will be temporary solution before better than for me

MutationObserver look like right for this problem but its work async. So if parent dom style(inline) change, event triggering but its not wait to domChanging end. its receiving old dom attributes, not new attributes.

Maybe someone give a recommend for this problem?






i worked on develop fork



```javascript
data(){
  return {
   _observer: null
   .
   .
   .
 }
},
mounted(){
.
.
.

 //check parent resizing
 this._observer = new MutationObserver(() => {
   setTimeout(() => this.checkParentSize(), 300);
 });

 this._observer.observe(this.$el.parentNode, {
   attributes: true,
   attributeFilter: ['style', 'class']
 });


},
beforeDestroy(){
.
.
.
 //remove parent resize observe
 this._observer.disconnect()

}
```

**Comment by mauricius** [comment]
Since you're using the `dev` branch, you can cheat a little bit and trigger manually the `window` resize event, which is used by the component to refresh the size of the parent element. Something like this, right after you change the size of the parent element:

```
window.dispatchEvent(new Event('resize'))
```
