### ISSUE TITLE
使用v-for创建多个实例的时候,每次都会在document上注册事件

### ISSUE THREAD

**Issue by helloDearD** [mauricius/vue-draggable-resizable#138]
使用v-for创建多个实例的时候,每次都会在document上注册事件,  mounted: function () {
    document.documentElement.addEventListener('mousemove', this.handleMove, true)
    document.documentElement.addEventListener('mousedown', this.deselect, true)
    document.documentElement.addEventListener('mouseup', this.handleUp, true)
    // touch events bindings
    document.documentElement.addEventListener('touchmove', this.handleMove, true)
    document.documentElement.addEventListener('touchend touchcancel', this.deselect, true)
    document.documentElement.addEventListener('touchstart', this.handleUp, true)
    document.documentElement.addEventListener('touchstart', this.deselect, true)
    this.elmX = parseInt(this.$el.style.left)
    this.elmY = parseInt(this.$el.style.top)
    this.elmW = this.$el.offsetWidth || this.$el.clientWidth
    this.elmH = this.$el.offsetHeight || this.$el.clientHeight
    this.reviewDimensions()
  },这样如果v-for 了1000个,就注册了一千次,浏览器就卡

**Comment by mauricius** [comment]
Yes, you're right! If you have one thousand instances of the component, the same events will be bind to the document one thousand times.

I'm not sure if it is possible to use event delegation or some other strategy to handle things differently, but I think that performances are acceptable for most use cases. Honestly I don't see the point of supporting up to one thousand instances.

An improvement has been made in version 2, in the sense that events are registered only when an element is active.

**Comment by helloDearD** [comment]
Yes, I also tried to change it and add an event to him when it is activated.
