### ISSUE TITLE
[Feature request] "always active" mode

### ISSUE THREAD

**Issue by plindelauf** [mauricius/vue-draggable-resizable#139]
I really like your component, but unfortunately it does not support one of our major use cases: our UI consists of a number of panels. The user should be able to resize them at any time, without having to click to active resizability (or draggability for that matter) first. Hence we're looking for some kind of "always active" mode. It would be great if this could be supported in the near future.

**Comment by plindelauf** [comment]
That works, @yoyoys . Thanks for that!
However, this eating unnecessary processing cycles, so instead of battling the component this way, it would be great if the component would simply support an "always active" mode.

**Comment by mauricius** [comment]
Sorry for the delay. Maybe the `preventDeactivation` [prop](https://github.com/mauricius/vue-draggable-resizable#preventdeactivation) can work for you. Define your components to be active by default and that prop will prevent deactivation when clicking outside them.

**Comment by antmihlin** [comment]
For some reason the property does not work. It is still being deactivated when I set 
`:prevent-deactivation="true"`
