### ISSUE TITLE
Dimension properties aren't reactive?

### ISSUE THREAD

**Issue by alphatrust-dev** [mauricius/vue-draggable-resizable#140]
Is the code example below, there doesn't seem to be a way of changing the dimension properties after the component is initialized.  The recreate, click on the link below, and click the "Move Fields" button and you'll see the properties change but the elements don't move to reflect the property changes.

https://codesandbox.io/s/ypooylrypv

**Comment by TitanFighter** [comment]
The props you need in v1 of this component is not reactive. Use v2 version from `dev` branch.

v2 from dev branch can be installed using `npm install https://github.com/mauricius/vue-draggable-resizable#develop --save`

Then in your main.js:

```
import VueDraggableResizable from 'vue-draggable-resizable/src/index'
import 'vue-draggable-resizable/src/components/vue-draggable-resizable.css'
Vue.component('vue-draggable-resizable', VueDraggableResizable)
```

**Comment by alphatrust-dev** [comment]
Thanks @TitanFighter -  I went to go try this in CodeSandbox.com and couldn't figure it out, did some googling and saw that you had this same issue: https://stackoverflow.com/questions/52937556/is-it-possible-to-import-js-module-from-github-dependency-in-case-of-using-codes

Did you ever figure out how to accomplish this in CodeSandbox?

**Comment by alphatrust-dev** [comment]
Also, when I add to my project using NPM, I get this error when I build:

```
ERROR in ./node_modules/vue-draggable-resizable/src/components/vue-draggable-resizable.vue 1:0
1>      Module parse failed: Unexpected token (1:0)
1>      You may need an appropriate loader to handle this file type.
1>      > <template>
1>      |   <div
1>      |     :style="style"
1>       @ ./node_modules/vue-draggable-resizable/src/index.js 3:0-62 3:0-62
1>       @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./App/components/workflow-designer/Templates/Workflows/TasksSetup.vue
1>       @ ./App/components/workflow-designer/Templates/Workflows/TasksSetup.vue
1>       @ ./App/routing/routes.js
1>       @ ./App/main.js
1>  npm ERR! code ELIFECYCLE
1>  npm ERR! errno 2
1>  npm ERR! aspnetcore-vuejs@ build: `webpack --mode development`
1>  npm ERR! Exit status 2
1>  npm ERR! 
1>  npm ERR! Failed at the aspnetcore-vuejs@ build script.
1>  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by TitanFighter** [comment]
I did not find the way how to run dev branch in codesandbox but with the steps provided above there are no any problems in case of development/production usage.

**Comment by alphatrust-dev** [comment]
Ah, I was trying to put them in the component directly instead of main.js, I think that's the issue.
