### ISSUE TITLE
accepting 'auto' width and height

### ISSUE THREAD

**Issue by chiu0602** [mauricius/vue-draggable-resizable#141]
Currently property "w" and "h" accepts only numbers, but 'auto' should be a valid input.
As a workaround, style="width:auto;height:auto" can fulfill my need, and it will be great if the plugin support accepting 'auto' value.

**Comment by mauricius** [comment]
Can you (or someone else) please provide me a concrete use case for why `auto` should be a valid input? Just asking, I'm not able to think about anything in concrete. Thanks

**Comment by chiu0602** [comment]
```
<vue-draggable-resizable :style="{ width: 'auto', height: 'auto' }">
  ...
<vue-draggable-resizable>
```

**Comment by chiu0602** [comment]
My dialog contains a table, with 'auto' width and height, it will show properly with:
```
<vue-draggable-resizable :style="{ width: 'auto', height: 'auto' }">
  ...
</vue-draggable-resizable>
```
But if I set it with a fix size, the dialog will be too big or too small (as the content of table varies). So I would like to have 'auto' value for width and height setting and let the browser decide the dimension of dialog.

Thanks.

**Comment by mauricius** [comment]
And does it need to be resizable as well? Because if it does I need to go back to specific values for width and height. I have something in mind that might work, but I want to be sure that it doesn't introduce unnecessary complexity.

**Comment by chiu0602** [comment]
For my case, no, so just accept 'auto' as value on validation will be perfect for me. It is better to have other enhancement suggestion by others.
Thanks for all for your contributions on this nice addon!

**Comment by HydrogenPan19** [comment]
I agree.
In most cases, we just need to add a drag feature to the widget.
Such as a floating search box, toolbar, etc.
I don't want to care about their size.

**Comment by Lmpgdn** [comment]
Do we have any updates for this feature?

**Comment by Radouch** [comment]
> And does it need to be resizable as well? Because if it does I need to go back to specific values for width and height. I have something in mind that might work, but I want to be sure that it doesn't introduce unnecessary complexity.

My use case is that I need **resizable** component (draggability is welcomed but not necessary) which will have **initial** height and/or width set to the height of its content (~ auto). 
Not sure if it is not overcomplicated to do.

**Comment by stasoft91** [comment]
At least please provide some redraw function callable from $refs.moveable.redrawBorders() or something. We colud catch that from inside component and fire nex. In my use case it is <video> with variable resolution (vertical\horizontal)

**Comment by stasoft91** [comment]
Aw, disregard that, i am probably going with 
```
      this.$refs.moveable.rawBottom =
        this.$refs.moveable.parentHeight -
        this.$refs.media.$refs.videoElem.clientHeight -
        this.$refs.moveable.rawTop
```

**Comment by mauricius** [comment]
See #220
