### ISSUE TITLE
Hold shift to select multiple objects and drag multiple objects at the same time,how?

### ISSUE THREAD

**Issue by wlinglinux** [mauricius/vue-draggable-resizable#147]

**Comment by shiyuegongsui** [comment]
I  have the same question~!!!!!!

**Comment by Alvin1128** [comment]
I have the same question~!!!!!!

**Comment by gongzemin** [comment]
I have the same question~!!!!!!

**Comment by TitanFighter** [comment]
There is no such functionality~!!!!!!

**Comment by mauricius** [comment]
https://github.com/mauricius/vue-draggable-resizable/issues/176#issuecomment-529116000
