### ISSUE TITLE
how to add: position: fixed && opportunity to attach widow

### ISSUE THREAD

**Issue by mioe** [mauricius/vue-draggable-resizable#148]
https://codesandbox.io/s/ywv587r001
salute, I wonder whether it is possible through add css position && opportunity select text in textarea (via props/event) ?
![s4lebidbyd](https://user-images.githubusercontent.com/16230771/52160814-f4937880-26cc-11e9-9063-4e8c73d57ce6.gif)

**Comment by mauricius** [comment]
You can totally use CSS to set the position `fixed` just like you did. Then you can use `x` and `y` props to set the position of the element, based on your requirements. I guess that if you want the component to have a fixed position then you don't want to make it draggable. Therefore use the [draggable](https://github.com/mauricius/vue-draggable-resizable#draggable) prop to disable this functionality. This will solve also the text selection problem.
