### ISSUE TITLE
Has anyone had success with syncing to Vuex?

### ISSUE THREAD

**Issue by liquidvisual** [mauricius/vue-draggable-resizable#149]
My draggable objects are stored inside Vuex. When a component drags, the @dragging event updates the Vuex store with the component's new X and Y positions, and this flows back down through to the vue-draggable-resizable component.

Sometimes it works, other times not. I think this might be creating a bottleneck due to the syncing stuff. The Vue dev tools start to get slow and the numbers don't update quickly.

Is there a proper way to do this?

**Comment by TitanFighter** [comment]
I had such problems with some other components. In my case nextTick helped.

**Comment by liquidvisual** [comment]
Thanks for your reply @TitanFighter. I'm probably going about this the wrong way, using Vuex to store the drag positions in real time. Feels a bit heavy.

Ultimately what I'm trying to achieve is to prevent the draggable window from exceeding the viewport and getting lost. Constraining to the parent isn't an option though. 

My first thought was to place a check on the @dragstop, so once the user releases the drag, it saves the position to Vuex. If the position is too far, it will correct the value and the window should "snap" back to the safe area.

Is that possible to do? How would you go about it?

**Comment by TitanFighter** [comment]
[Here at the end of the article](https://itnext.io/anyway-this-is-how-to-use-v-model-with-vuex-computed-setter-in-action-320eb682c976) you can find examples of how to use set() get(). Maybe it can help. If not -> show demo, for example using [codesandbox.io](codesandbox.io).

**Comment by liquidvisual** [comment]
Great, I'll check it out - thanks. I'll try and put together an example in CodeSandbox soon.
