### ISSUE TITLE
Some advices and issues

### ISSUE THREAD

**Issue by eyelandlau** [mauricius/vue-draggable-resizable#15]
Hello, I am from China so excuse me for any mistakes since my not-so-good English.
I add a pseudo-class after Class active just like this:
`.active:after {
    content:"";
    display: block;
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
    box-sizing: border-box;
    border: 1px dashed;
  }`,
I think it could be more clear when user is choosing an component and dragging it.
The maximize function should be optional and I don't like it most of time because its animation is too long.

The props of 'x' and 'y' have validator that must more than 0. That led to I can't drag it over the left or the top of its parent element even when I didn't set the 'parent' prop into true .Is there any reason to do this ? I don't think it is a good idea.

After all , this component is so great and I like it very much.

**Comment by eyelandlau** [comment]
Here is another advice:
I think the event 'deactivated' should be emit while the active turns to false. My app has so many compontent use _vue-draggable-resizable_ ,so when I use Vue devtool to debug my code, the console alway stick cause the 'deactivated' event is emit when I click anywhere in dom, but most of them are not the real deactivated.

**Comment by mauricius** [comment]
> I add a pseudo-class after Class active just like this. I think it could be more clear when user is choosing an component and dragging it.

Sure, but I really wanted to use as few css rules as possible. So every user can style the component as he needs.

> The maximize function should be optional and I don't like it most of time because its animation is too long.

It is optional. Take a look at the [maximize prop](https://github.com/mauricius/vue-draggable-resizable#maximize).

> The props of 'x' and 'y' have validator that must more than 0. That led to I can't drag it over the left or the top of its parent element even when I didn't set the 'parent' prop into true .Is there any reason to do this ?

You can remove the `position: relative` rule from the parent element, so you can also move the component outside it. Its position will be then calculated relatively from the relative node up in the dom tree, until `body` is reached.

> I think the event 'deactivated' should be emit while the active turns to false

You're right. I'll fix it in the next release.

**Comment by eyelandlau** [comment]
oops, there is another issue:
In your methods "elmDown", you get the element's width and height and set into 'elmW' and ‘elmH’, but the function 'offsetWidth' and 'offsetHeight' will take the elements attributes and turn it into integer, so when I click my elment, it will a little smaller.
I think you can try to get the style first, like this:
`this.elmW = parseFloat(this.$el.style.width) || this.$el.offsetWidth || this.$el.clientWidth`

**Comment by eyelandlau** [comment]
@mauricius

**Comment by eyelandlau** [comment]
@mauricius 
Your mousedown event bind in document, so when I use this plugin, I cant drag to select any word in input

**Comment by mauricius** [comment]
> In your methods "elmDown", you get the element's width and height and set into 'elmW' and ‘elmH’, but the function 'offsetWidth' and 'offsetHeight' will take the elements attributes and turn it into integer, so when I click my elment, it will a little smaller.

Actually I prefer to stick with integers, in order to simplify the calculations. However, can you show me an example of this particular case, so I can take a look?

> Your mousedown event bind in document, so when I use this plugin, I cant drag to select any word in input

Fixed in 632392fdfbf7b2c14c65c728cb46463b1ffe671f by testing if the click event comes from an input or a textarea. It also seems that the native browser implementation is buggy, for example [http://jsfiddle.net/k43QZ/1/](http://jsfiddle.net/k43QZ/1/) and [http://jsfiddle.net/s5g4gr8g/](http://jsfiddle.net/s5g4gr8g/)
