### ISSUE TITLE
How to use vue-draggable-resizable in typescript env ?

### ISSUE THREAD

**Issue by moketao** [mauricius/vue-draggable-resizable#151]
i try to use vue-draggable-resizable in a TypeScript + Vue project ... but fail ...

here is the errer msg：
`Try `npm install @types/vue-draggable-resizable` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-draggable-resizable';`

is there a quick way to gen a .d.ts file for vue-draggable-resizable ？

**Comment by mauricius** [comment]
Unfortunately I'm not so familiar with TypeScript and that's why the library does not include type definitions. However I think you can try to import the module with CommonJS syntax `const VueDraggableResizable = require("vue-draggable-resizable");`.

**Comment by simpleoo0o** [comment]
```
// @ts-ignore
import VueDraggableResizable from '@plantdata/vue-draggable-resizable';
```

**Comment by yilingsj** [comment]
其实有很多库在ts中使用时都会 **报@types/库名** 的错误，其实你可以在项目中的
`shims-vue.d.ts` 文件中添加
`declare module 'vue-draggable-resizable'`
这行代码即可解决问题，附带自己上周前的一个试水项目截图。
![在ts中使用](https://img.alicdn.com/imgextra/i3/759415648/O1CN01Zjmgm91rapYjYAwGn_!!759415648.png)
