### ISSUE TITLE
Keep draggable element active until explicitly forcing deactivation

### ISSUE THREAD

**Issue by alphatrust-dev** [mauricius/vue-draggable-resizable#152]
I want to click on a draggable item to activate it (which happens fine currently), have that click trigger an event for a properties window to open up (I can make this happen currently as well with no problem) so I can edit the properties of the element (when I do this, the element automatically deactivates - which I don't want), and then click a "close" button to manually deactivate the selection.  Basically, I'd like for the deactivation to never happen unless I explicitly trigger the event in my code.  Is that possible?

**Comment by mauricius** [comment]
Sure you can! Use `preventDeactivation` [prop](https://github.com/mauricius/vue-draggable-resizable#preventdeactivation) to avoid deselecting the component when clicking outside it. Then use the `active` prop to sync your state with the component, so you can decide when deactivate it. Optionally you can also use the `sync` [modifier](https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier) to update your state when the internal value changes.

```
<vue-draggable-resizable :prevent-deactivation="true" :active.sync="active">
...
</vue-draggable-resizable>
```

**Comment by alphatrust-dev** [comment]
PERFECT!
