### ISSUE TITLE
ContextMenu does not work

### ISSUE THREAD

**Issue by mirkofisic** [mauricius/vue-draggable-resizable#159]
@contextmenu event does not work.

**Comment by gianlucariccobono** [comment]
@mirkofisic I am just struggling with this issue too right now. Did you had any success finding a solution?

**Comment by jeisele2** [comment]
I haven't solved, but try @contextmenu.native.prevent="yourhandler"

**Comment by mauricius** [comment]
Are you using the component in combination with this one https://github.com/rawilk/vue-context? I just tried and I did not have any issues. See screenshot. What kind of problem are you having?
![2019-07-26 21 27 22](https://user-images.githubusercontent.com/7000852/61976543-5d104200-afec-11e9-95f1-ca6c64324303.gif)
