### ISSUE TITLE
How to distinguish between multiple components in event handler

### ISSUE THREAD

**Issue by ScorpioX** [mauricius/vue-draggable-resizable#16]
Currently event handlers like _resizestop_ only receive dimension values like [x, y, w, h], which is not enough to tell which component just got resized.

A suggested solution is to allow an addition prop as unique ID.

Even better, accept a component configuration object, which shall include all necessary configurations, and in case of move or resize, all dimensional values could be directly altered directly in the configuration

**Comment by lmr2391** [comment]
Don't you attach the event handler to a `vue-draggable-resizable`? If you do that, you should automatically know which component got resized and can pass that to your event handling function.

**Comment by mauricius** [comment]
@ScorpioX you can use function composition to achieve your purpose. Take a look at this example.
```html
<template>
  <div id="app">
    <div style="height: 500px; width: 500px; margin: 20px; border: 1px solid red; position: relative;">
      <template v-for="element in elements">
        <vue-draggable-resizable :parent="true" :resizable="true" :x="element.x" :y="element.y" style="border: 1px solid" @resizing="(left, top, width, height) => onResizing(element.id, left, top, width, height)">
          <p>{{ element.id }}</p>
        </vue-draggable-resizable>
      </template>
    </div>
    <button @click="change">Cambia posizione</button>
  </div>
</template>
```

```javascript
export default {
  data () {
    return {
      elements: [
        {
          id: 'one',
          x: 0,
          y: 0
        },
        {
          id: 'two',
          x: 100,
          y: 0
        },
        {
          id: 'three',
          x: 0,
          y: 100
        }
      ]
    }
  },
  methods: {
    onResizing (id, left, top, width, height) {
      console.log(id, left, top, width, height)
    }
  }
}
```

**Comment by ScorpioX** [comment]
@mauricius I've made a quick and dirty hack of your original version [here](https://github.com/ScorpioX/vue-draggable-resizable) which uses a cfg object to simplify props and params exchange without events. It's for an PowerPoint like editor which shall support dozens of objects with lots defaults (parent, resizable, e.g.) pre-set.

Anyway, thanks a lot for your brilliant work without which our project would not be possible. Drop me a note anytime in case you need further details on my project 8>

**Comment by mauricius** [comment]
> Anyway, thanks a lot for your brilliant work without which our project would not be possible. Drop me a note anytime in case you need further details on my project 8>

Sure! I would love to see where the component is used. Feel free to ping me when you have something available. Thanks!
