### ISSUE TITLE
How to Set Equal Ratio Scaling

### ISSUE THREAD

**Issue by cgletufo** [mauricius/vue-draggable-resizable#161]
Keep the same proportion when dragging and zooming

**Comment by mauricius** [comment]
See [prop](https://github.com/mauricius/vue-draggable-resizable#lockaspectratio) and [demo](https://mauricius.github.io/vue-draggable-resizable/?selectedKind=Aspect%20Ratio&selectedStory=Basic%20Aspect%20Ratio&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel)
