### ISSUE TITLE
Resizing Handles are not displayed when using a custom scoped style

### ISSUE THREAD

**Issue by jeremco** [mauricius/vue-draggable-resizable#163]
Hi 
Using the component in a vue application with scoped style tag, resizing handles are not displayed. If I choose a class-name-handle style, they are not displayed as well. 

```
<template>
  <div id="app">
    <div style="height: 500px; width: 500px; border: 1px solid red; position: relative;">
      <vue-draggable-resizable :w="400" :h="400" :parent="true" :debug="false" :min-width="200" :min-height="200" class-name-handle="my-handle-class">
        <p>vue-draggable-resizable</p>
      </vue-draggable-resizable>
    </div>
  </div>
</template>

<style scoped>

...
.my-handle-class {
    position: absolute;
    background-color: pink;
    border: 1px solid black;
    border-radius: 50%;
    height: 14px;
    width: 14px;
    box-model: border-box;
    -webkit-transition: all 300ms linear;
    -ms-transition: all 300ms linear;
    transition: all 300ms linear;
  }

  .my-handle-class-tl {
    top: -14px;
    left: -14px;
    cursor: nw-resize;
  }
....
</style>
```

The issue can be reproduced using attached App.vue (derivated from source App.vue)
[App.vue.txt](https://github.com/mauricius/vue-draggable-resizable/files/3201346/App.vue.txt)

Jeremie

**Comment by mauricius** [comment]
Of course. `scoped` adds the class to the component only when the style declaration matches the `class` attribute. In this case you are passing a prop to the component so Vue is unaware of your intentions.

You can solve this problem by using [deep selectors](https://vue-loader.vuejs.org/guide/scoped-css.html#deep-selectors), so you can apply scoped classes to child elements.

```
<template>
  <div id="app">
    <div style="height: 500px; width: 500px; border: 1px solid red; position: relative;">
      <vue-draggable-resizable class="custom-handles" :w="400" :h="400" :parent="true" :min-width="200" :min-height="200" class-name-handle="my-handle-class">
        <p>vue-draggable-resizable</p>
      </vue-draggable-resizable>
    </div>
  </div>
</template>

<style scoped>
.custom-handles >>> .my-handle-class {
  position: absolute;
  background-color: pink;
  border: 1px solid black;
  border-radius: 50%;
  height: 14px;
  width: 14px;
  box-model: border-box;
  -webkit-transition: all 300ms linear;
  -ms-transition: all 300ms linear;
  transition: all 300ms linear;
}

.custom-handles >>> .my-handle-class-tl {
  top: -14px;
  left: -14px;
  cursor: nw-resize;
}
</style>
```

This way `.custom-handles >>> .my-handle-class` will compile to something like `.custom-handles[data-v-7ba5bd90] .my-handle-class` allowing you to apply the style to the child element.

**Comment by jeremco** [comment]
Hi

Yes you're right.
I have forgotten this feature. It's working this way.

Thank you.
I close this issue
