### ISSUE TITLE
how to set init position bottom and rignt?

### ISSUE THREAD

**Issue by xxbld** [mauricius/vue-draggable-resizable#165]
i need set the  BR position at  first time,but props x and y only TL
<Parent>
    <VueDraggableResizable initPositon='right:0px;bottom:0px;'>
        <Content />
    </VueDraggableResizable >
</Parent>

**Comment by VladStepanov** [comment]
If i correctly understand, u can assign init value like
`
this.x = this.item.x;
this.y = this.item.y;
`
and update coords by dragging
`
dragging(x, y) {
  this.x = x
  this.y = y
}
`

**Comment by TitanFighter** [comment]
Show your code
