### ISSUE TITLE
Allow dragging & resizing to initial values

### ISSUE THREAD

**Issue by adrianhurt** [mauricius/vue-draggable-resizable#167]
Hi, I've observed once you start a dragging or resizing movement it's imposible to finish with the initial values.

I think this is due to these lines: [1](https://github.com/mauricius/vue-draggable-resizable/blob/1dc38b8b61bcddd08f280ad87f0762a34536fbbc/src/components/vue-draggable-resizable.vue#L542) and [2](https://github.com/mauricius/vue-draggable-resizable/blob/1dc38b8b61bcddd08f280ad87f0762a34536fbbc/src/components/vue-draggable-resizable.vue#L560).

The problem here is that if you regret dragging or resizing the only chance is finish it with undesired values and then change it again to the initial ones.

Thanks for this great library!!

**Comment by TitanFighter** [comment]
You can try to implement it yourself. When you start dragging or resizing, just store the coordinates of initial position. Then if you regret about it, click a button like 'Restore' and restore it using saved coordinates.

**Comment by adrianhurt** [comment]
Yes, but the problem is that if you are dragging or resizing, you have to finish it, and then "restore" the initial state (dragging or resizing again or with a button, it's indifferent).

At least in my case, I often drag accidentally an item, so I want to place it as before (or press 'esc' key or something). On other hand, a user may want to drag an item and finally place it at the original point (he regret or even he could forget the original point).

It could seem a minor issue, but you could have some side effects when you move an item.

IMHO, I don't understand the reason to avoid finish a dragging at the original position. I suppose there is some implementation reason, but it's strange as an UX point of view.

**Comment by mauricius** [comment]
Thanks @adrianhurt, it's definitely a bug and honestly I never noticed that behavior, even after using the component so many times. I'm going to submit a fix in the next few days.
