### ISSUE TITLE
How can I use this plugin for nested objects?

### ISSUE THREAD

**Issue by Markeldo** [mauricius/vue-draggable-resizable#168]
Hi. I have a structure like this: there're some boxes in a room and some items in boxes. I need to have an option to move boxes in room and items in a box. So I can do it with nested vue-draggable-resizable.
But when I did it, I can move only boxes, not items. =(
Is there any method to deactivate parent vdr when I draggin' child vdr?

**Comment by mauricius** [comment]
You can try to use the `onDragStart` [callback](https://github.com/mauricius/vue-draggable-resizable/#ondragstart) to prevent dragging in the parent component.

**Comment by Markeldo** [comment]
> You can try to use the `onDragStart` [callback](https://github.com/mauricius/vue-draggable-resizable/#ondragstart) to prevent dragging in the parent component.

Thanks. That worked.

**Comment by Markeldo** [comment]
Looks like it didn't work out. Now I can undo the move of the parent element and in theory move the child. However, when you try to move, the child block sticks to the right border of the parent block tightly. As a result, I can move the element along the Y-axis, but on the X-axis it is tied rigidly to the parent. I can't figure out what went wrong. If you remove from the container in the parent block parent="true", the child can be moved without problems, but then it can naturally be taken out of the parent element, and this is not what I need... =(

**Comment by Markeldo** [comment]
Oh... that was my bad. In parent draggable I placed div with "width: 100%; height: 40px" for children. So children wasn't able to get right width of their parent. Setting width in pixels helped.
