### ISSUE TITLE
script-code in documentation

### ISSUE THREAD

**Issue by larsrinn** [mauricius/vue-draggable-resizable#17]
Currently the documentation only shows the html but not the `<script> [....] </script>` part of the apps. However, it would be nice to be able to see how the event handlers are called, etc. Do you think it should be included in the documentation? If so, I could do that and send a pr, if you like

**Comment by mauricius** [comment]
Sure, why not? Also feel free to redesign the documentation page, if you feel comfortable. As you can see I'm not a good designer.
