### ISSUE TITLE
can add rotation feature?

### ISSUE THREAD

**Issue by Alvin1128** [mauricius/vue-draggable-resizable#173]
![38343177-f8148316-38b4-11e8-9e3f-cb5623ed160d](https://user-images.githubusercontent.com/12343433/61169046-d68a4800-a589-11e9-89a1-8ac3cae42fb8.gif)

Hi，if can support rotation feature  like this , it's very useful.

@mauricius

**Comment by gorkys** [comment]
@Alvin1128 
我想你可以看一看#91，不过我知道有一个旧版本的修改版增加了旋转功能。https://github.com/tmrcui/vue-draggable-resizable-rotatable

**Comment by mauricius** [comment]
Take a look also at this project https://github.com/probil/vue-moveable
