### ISSUE TITLE
Move handle inside draggable?

### ISSUE THREAD

**Issue by edwh** [mauricius/vue-draggable-resizable#177]
I'm trying to style a handle and move it inside the draggable element, rather than have it outside.  This is using active=true and prevent-deactivation=true - if you do those then the handles always appear, but they look messy in my application outside the element, so I want them to be inside on a title bar.

I'm trying to do it using this CSS:

```
.handle-tl {
  content: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH4AQLDigeVd0uIAAAAHpJREFUOMvVkDEKgDAMRQuOLoIHcHTUybmb4BW8gPQM4tWfg6mUIJRmUf+W8P9/JM59RkAHBACZK2Dh0ii7GtiiRxcEMQ8yx/ABtBJeZeefCgB6Rd41GZhzp9xhoMmSk+BLZPWDcnJSMJnIqqScrMI2shTYyOqJ3v1OJ4UMEzPeJauEAAAAAElFTkSuQmCC');
  height: 16px;
  width: 16px;
  top: 16px;
  position: relative;
}
```

But once it moves inside, I can no longer grab it and drag.  If I remove the position: relative, then it moves outside and then I can drag it.  

Any suggestions?

**Comment by mauricius** [comment]
You definitely have to remove `position: relative` from your style. It works for the top-left handle but of course not for the other handles. Just use `position: absolute` and adjust the position for each one.

Here's how you can do it:

```
.handle {
  content: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QAAAAAAAD5Q7t/AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH4AQLDigeVd0uIAAAAHpJREFUOMvVkDEKgDAMRQuOLoIHcHTUybmb4BW8gPQM4tWfg6mUIJRmUf+W8P9/JM59RkAHBACZK2Dh0ii7GtiiRxcEMQ8yx/ABtBJeZeefCgB6Rd41GZhzp9xhoMmSk+BLZPWDcnJSMJnIqqScrMI2shTYyOqJ3v1OJ4UMEzPeJauEAAAAAElFTkSuQmCC');
  height: 16px;
  width: 16px;
  position: absolute;
  background-color: red;
}
.handle-tl {
  top: 0;
  left: 0;
}
.handle-tr {
  top: 0;
  right: 0;
}
.handle-bl {
  bottom: 0;
  left: 0;
}
.handle-br {
  bottom: 0;
  right: 0;
}
.handle-tm {
  top: 0;
  left: 50%;
}
.handle-ml {
  top: 50%;
  left: 0;
}
.handle-mr {
  top: 50%;
  right: 0;
}
.handle-bm {
  bottom: 0;
  left: 50%;
}
```

And the result
![Schermata da 2019-09-07 13-23-09](https://user-images.githubusercontent.com/7000852/64474284-88ea2000-d173-11e9-8587-b43b1160daff.png)

**Comment by edwh** [comment]
Thanks very much.

In my example I also had to set z-index, otherwise the handle didn't 
seem to be capturing the event.

------ Original Message ------
