### ISSUE TITLE
Can we resize and drag programmatically?

### ISSUE THREAD

**Issue by mudin** [mauricius/vue-draggable-resizable#183]

**Comment by TitanFighter** [comment]
https://mauricius.github.io/vue-draggable-resizable/?selectedKind=Basic&selectedStory=Basic%20controlled%20component&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fnotes%2Fpanel

**Comment by mudin** [comment]
@TitanFighter Thanks, How come I missed see this example. But I already tried to change `x` and `y`, since it was negative value it didn't work.

**Comment by TitanFighter** [comment]
Show your code via codesandbox or similar service.

**Comment by TitanFighter** [comment]
Hi @mauricius 
It seems to be a bug. If user selects `vue-draggable-resizable` and as a results activates `@activated="someFunction"`, the component stops listening any changes. For example if I want to change `x` inside `someFunction`, the value `x` changes, but the component does not react on this change. I can guess that while `vue-draggable-resizable` is active, it does not listen anything.

**Comment by Lmpgdn** [comment]
> For example:
> 
> 1. I activate the component;
> 2. It triggers `@activated="someFunction"`;
> 3. I change `this.x += 50` inside `someFunction` -> I see that the value `this.x` changes, but the component does not react on this change.

I am also experiencing this issue.

**Comment by mauricius** [comment]
Unfortunately this is a know issue. When the component is activated it enters in a "draggable" state which disables watching `x`, `y`, `w` and `h` props to avoid external interference during dragging. Changing those props after the `activated` event therefore has no effect. I don't feel like removing such checks will be beneficial at all and it could introduce more problems.

@tgmoore you can achieve the same result by using the `dragstop` [event](https://github.com/mauricius/vue-draggable-resizable#dragstop) which is fired after a mouseup event after dragging, but also after the activation of the component. Hopefully this works for you. See the updated fiddle

https://jsfiddle.net/vsp7xfg5/

**Comment by AndersBKnudsen** [comment]
I have tried to hook in on mounted to set the X and Y so it gets moved to a element depending on the screen size. 

<vue-draggable-resizable :x="x" :y="y">

  mounted () {
    var teamContainerRect = document.getElementById('teamContainer').getBoundingClientRect();
    this.x = teamContainerRect.left;
    this.y = teamContainerRect.top;
  }

When I print the value they are correct, but my draggle doesn't move to the position.
It moves if I set the this.x = 100 in mounted.

How come?

**Comment by eliyaho-chananya** [comment]
i do it but its a little tricky. im actually touch the component data 

[https://jsfiddle.net/txqhe41d/](url)

this is just example how to add h and w of course in the real project you should check and do all the math if its should be a negative number (for add w\h) or positive number (for decrease the w/h)

**Comment by KuenzelIT** [comment]
Is it now possible to programmatically change the x und y position? I want to set the position using a text input.

**Comment by TitanFighter** [comment]
@KuenzelIT check https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-controlled-component

**Comment by KuenzelIT** [comment]
Thank you, I got it working now!

I assume this issue can be closed?

**Comment by TitanFighter** [comment]
Yes

**Comment by mudin** [comment]
I think found the reason of this issue. 
If I set the integer values, it is resizing and dragging programatically!
