### ISSUE TITLE
Webpack / npm  issue with ^2.0.0 version

### ISSUE THREAD

**Issue by obaudouin** [mauricius/vue-draggable-resizable#184]
Context: Webpack, npm, Laravel

No matter with version 2.0.0-rc2, npm run dev succeeds

But compilation fails after updating to version 2.0.0:

> Module not found: Error: Can't resolve 'vue-draggable-resizable'
```
window.Vue = require('vue');
window.VueDraggableResizable = require('vue-draggable-resizable'); // fails here
```
But the package is correctly installed in the node_module folder...

Thanks!

**Comment by mauricius** [comment]
Sorry for that! I messed up with the publish command. Please try again with 2.0.1.
