### ISSUE TITLE
Parent CSS Selector not working/implemented as mentioned

### ISSUE THREAD

**Issue by HackXIt** [mauricius/vue-draggable-resizable#186]
The "parent" prop description mentions the ability to use CSS selectors for this prop, instead of the boolean type.

> parent
> 
> Type: Boolean | String
> Required: false
> Default: false
> 
> Restricts the movement and the dimensions of the component to the parent (if true is provided), or to an element identified by a valid CSS selector.
> 
> `<vue-draggable-resizable :parent="true">`
> 
> `<vue-draggable-resizable :parent=".selector">`

But when using a valid CSS selector the compilation fails with the following:

> Errors compiling template:
> 
>   invalid expression: Unexpected token . in
> 
>     .container
> 
>   Raw expression: :parent=".container"
> 
> 
>   13 |        :key="index"
>   14 |        :w="50"
>   15 |        :h="50"
>      |                
>   16 |        :parent=".container"
>      |  ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   17 |        :resizable="false"
> 
>   invalid expression: Unexpected token . in
> 
>     .container

When checking the code, the prop is implemented like this:

```
// ...
parent: {
      type: Boolean,
      default: false
    },
// ...
```

Is this feature even implemented yet? Will it be implemented?
Or am I just using this wrong?

Note: The used CSS selector '.container' mentioned is inside a 'scoped' style tag of the template.

**Comment by mauricius** [comment]
Sorry about that... I removed that feature [a few months ago](https://github.com/mauricius/vue-draggable-resizable/commit/1dc38b8b61bcddd08f280ad87f0762a34536fbbc) because it was causing issues. Of course, I have been careless enough to leave the documentation untouched. I'm going to update it as soon as possible.

**Comment by HackXIt** [comment]
Oh that's too bad. But thanks for the response.
