### ISSUE TITLE
Prevent multiple elements overlapping/colliding

### ISSUE THREAD

**Issue by alekbless** [mauricius/vue-draggable-resizable#195]
Hello! 

When dealing with multiple VueDraggableResizable components should we be able to prevent overlapping/colliding elements? 

Like this; 

<img width="315" alt="Skjermbilde 2019-12-02 kl  15 59 23" src="https://user-images.githubusercontent.com/6172971/69969468-c402b200-151c-11ea-8e99-74a1f96af031.png">

Not overlapping/colloding:

<img width="426" alt="Skjermbilde 2019-12-02 kl  15 59 34" src="https://user-images.githubusercontent.com/6172971/69969512-d5e45500-151c-11ea-8a72-c40cb238edd7.png">

**Comment by gorkys** [comment]
@alekbless see <https://github.com/gorkys/vue-draggable-resizable-gorkys>
