### ISSUE TITLE
Resize handle does not display

### ISSUE THREAD

**Issue by skywalkershen** [mauricius/vue-draggable-resizable#198]
Hi, I'm wrapping my single file component with draggable resizable, the dragging works, yet the resize handles appear to be of 0 height and 100% container width. 

I'm using the tag like this:
<vue-draggable-resizable  :x='x' :y='y' :w='width' :h='height' :parent='true' :active="true" v-if='show' @click='setToTop' :style='{"z-index": zIndex}' :class='{"isBelow": isBelow}'>

the width and height are set to be: 
                x: 1000,
                width:396,
                height: 1000
The sizing for all the handles are 396 * 0, and they don't show up even after I changed their height and z-index.

![image](https://user-images.githubusercontent.com/32822916/71050832-41ffc380-2181-11ea-90e6-fb72117e3c1e.png)

Please help, thanks.

**Comment by mauricius** [comment]
Please provide a basic example of the issue using https://jsfiddle.net/ or https://codepen.io/

**Comment by milost1982** [comment]
This is a bug, I don't see resize handles also... just installed your package with: npm i vue-draggable-resizable
and used simples example:

<vue-draggable-resizable >
  <p>test 123</p>
</vue-draggable-resizable>

This should be resizable by default but it's not. It's not even when I set prop :resizable="true".
It's only draggable though...

**Comment by mauricius** [comment]
[Make sure](https://github.com/mauricius/vue-draggable-resizable#install-and-basic-usage) to import also the CSS file, otherwise you have to provide rules for the handles by yourself.
