### ISSUE TITLE
Set X and Y depending on div

### ISSUE THREAD

**Issue by AndersBKnudsen** [mauricius/vue-draggable-resizable#204]
Hello

I want to set the start position depending on the position of a container. 

I am overloading the mounted by

  mounted () {
    var teamContainerRect = document.getElementById('teamContainer').getBoundingClientRect();
    this.x = teamContainerRect.left;
    this.y = teamContainerRect.top;
  }

This vue draggable is set with vue-draggable-resizable :x="x" :y="y"

But it doesn't move eventhough the X and Y contains the correct value.

It works if I set the values in mounted with a given value. 
mounted () {
   this.x = 100;
    this.y = 100;
  }

How come?

**Comment by TitanFighter** [comment]
Use codesandbox or anything else for minimal example then I can help you.

**Comment by AndersBKnudsen** [comment]
> Use codesandbox or anything else for minimal example then I can help you.

Sure. Basic sample. I have used typescript for project, but the example is js. 

https://codesandbox.io/s/frosty-star-9h108

In the component "hello World", I have written the example above.

**Comment by TitanFighter** [comment]
`this.x = teamContainerRect.left;` in your example is float.

Change it to `this.x = Math.round(teamContainerRect.left);` to make it integer.

**Comment by AndersBKnudsen** [comment]
You are so right! It makes sense. Thanks! :)
