### ISSUE TITLE
有关parent的大小设定。

### ISSUE THREAD

**Issue by zhfjgl** [mauricius/vue-draggable-resizable#206]
vue-draggbale-res这个标签的parent只能设定一次，修改parent的尺寸后，范围依然是最初的大小。
比如给的例子中https://mauricius.github.io/vue-draggable-resizable/?path=/story/parent--parent-basic-case，通过放大和缩小改变大小，v-d-r这个元素不会局限于div 中。

**Comment by mauricius** [comment]
Yes it looks like that, but in that example the zoom of Storybook changes the CSS `scale` property of one of the root nodes. The size definitely looks different, but in reality it isn't.

**Comment by JiaweiUTSCHINA** [comment]
可以使用this.$nextTick(() => {...}}和v-if搭配，强制重新加载即可解决这个parent问题

**Comment by sushuier** [comment]
> 可以使用this.$nextTick(() => {...}}和v-if搭配，强制重新加载即可解决这个parent问题

然鹅，这种办法看起来就傻傻的；而且很麻烦；

如果该插件能提供一个 update 方法，触发重新渲染就好了；

谷歌翻译：@mauricius
However, this method seems silly and troublesome;
It would be nice if the plug-in could provide an update method to trigger re-rendering;

**Comment by sushuier** [comment]
@codezhanghefei 
在动态修改父容器大小后，执行：
this.$nextTick(() => {
    this.$refs.vdr.checkParentSize();
});
即可重新触发父容器大小的设定；子元素的位置计算，x y什么的就都正常了；

**Comment by sushuier** [comment]
2025-08-22跟进：
当动态调整浏览器窗口时，某些情况下会动态调整 vue-draggable-resizable 内部元素的尺寸，导致 vue-draggable-resizable初始化获取的width和height不准确；也会影响drag时的边界判定；
When dynamically resizing the browser window, the dimensions of elements inside vue-draggable-resizable may be adjusted dynamically in some cases. This causes the width and height obtained during the initialization of vue-draggable-resizable to be inaccurate and also affects the boundary judgment during dragging.    (—— The translation is from Doubao AI.)

源码（source code）: 
mounted:  function () {
   //... code

   this.initRect();
   b(window, "resize", this.resize);
},
methods: {
  resize () {
     this.initRect();
     this.checkParentSize();
  },
  initRect() {
    const [i, s] = N(this.$el);
     this.width = this.w !== "auto" ? this.w : i;
     this.height = this.h !== "auto" ? this.h : s;
     this.right = this.parentWidth - this.width - this.left;
     this.bottom = this.parentHeight - this.height - this.top;
     // ... code
  },
}

目前解决办法是：w 和 h不能用 auto；用固定的值，需要动态修改内容尺寸时时，同步修改w和h即可；
The current solution is: w and h cannot use "auto"; use fixed values. When dynamic modification of the content size is required, simply modify w and h synchronously.    (—— The translation is from Doubao AI.)
