### ISSUE TITLE
Remove default from "h" prop and use "minHeight" for initial rendering height.

### ISSUE THREAD

**Issue by onyx-blackbird** [mauricius/vue-draggable-resizable#214]
The height prop, "h" is not mandatory, but has a default. I have rather dynamic content for example from an Rich Text Editor. So I only enable the 'mr' handle to be able to change the width. The height should then be evaluated from the content. So, it would make sense to have "h" be really optional without a default. The component should then just render to the "minHeight".

I know it is related to https://github.com/mauricius/vue-draggable-resizable/issues/194 but not exactly the same.

**Comment by onyx-blackbird** [comment]
I tried to solve this with an event handler; the inner component emits the height it needs.
Parent code:
```
public onComponentRendered(height: number) {
	this.height = height;
}
```
Parent template:
```
<vue-draggable-resizable :w="width" :h="height">
	<component :is="componentType" :data="element.data" @component-rendered="onComponentRendered"></component>
</vue-draggable-resizable>
```

Child Code (in this case for an image:
```
@Emit('component-rendered')
public onLoad(event: Event) {
	const img: HTMLImageElement = event.target as HTMLImageElement;
	if (img) {
		return img.naturalHeight;
	}
	return 20;
}
```
Child template:
`<img :src="src" @load="onLoad($event)">`

But this doesn't work, the vue-draggable-resizable stays the same.

**Comment by mauricius** [comment]
See #220 

Thanks
