### ISSUE TITLE
drag-cancel element does not cancel the first drag after activation (touchscreen only)

### ISSUE THREAD

**Issue by colin-guyon** [mauricius/vue-draggable-resizable#215]
You can easily reproduce the bug in this demo: https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-drag-cancel

1. Be sure you are in touchscreen mode (using the device mode of chrome dev tools, if you don't have a real touchscreen)
2. Activate the component, doing a single touch on it without trying to drag the item (not on the dragcancel area)
3. Try do drag the item touching the dragcancel area: the component moves, but it should not
4. If you try to do another drag touching the dragcancel area, the component does not move anymore, as expected.

Thanks

**Comment by mauricius** [comment]
Thanks for reporting! This will be fixed in the next version.
