### ISSUE TITLE
Componet behaves strange while parent size can‘t be deviced by grid

### ISSUE THREAD

**Issue by MaxYYYYY** [mauricius/vue-draggable-resizable#219]
![parent-grid-issue](https://user-images.githubusercontent.com/30397306/76686372-c0bbae00-6655-11ea-8a91-04cad83fd408.gif)

I change grid to [24,24] in story book, the parent size is 400 * 400, the limit's calculation seems changing while dragging the compent to edge.

Is that by design? Is that any to make componet's sides always close to parent's sides when I drag or resize the compnent to parent edge? 

Thanks!

**Comment by mauricius** [comment]
This is definitely a bug! I will fix it in the next version, which will be available in the next few days. Thanks for reporting.
