### ISSUE TITLE
unable to select text in input field within draggable wrapper

### ISSUE THREAD

**Issue by smg99** [mauricius/vue-draggable-resizable#222]
Hey Thanks for the amazing library. 

I have been trying to select text entered in an input field (using mouse) withing my vue-draggable-resizable wrapper. Its not selecting text and dragging the whole wrapper around. I tried using @click.stop.prevent and @click.prevent however that didn't worked. 

Any thoughts to achieve the desired input text selection?

**Comment by TitanFighter** [comment]
Did you try this[](https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-form-inside) ?

**Comment by smg99** [comment]
@titan

> Did you try [this](https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-form-inside) ?

It does also have the issue. Enclosed gif.
![Copy](https://user-images.githubusercontent.com/7676130/78523293-de5fdb80-77ed-11ea-8434-7a383df10a86.gif)

**Comment by TitanFighter** [comment]
Try to add `drag-cancel` as shown [here](https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-drag-cancel)

**Comment by smg99** [comment]
> Try to add `drag-cancel` as shown [here](https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-drag-cancel)

That worked ! Thanks a lot for rapid update :)
