### ISSUE TITLE
[Question] Addition parameters for event handler

### ISSUE THREAD

**Issue by dikkini** [mauricius/vue-draggable-resizable#235]
Hello!
Cool work!

I have this vue-draggable-resizable element with handler, for an example `@resizestop`.
```javascript
<vue-draggable-resizable :parent="true"
 @resizestop ="on_resizestop_expression"
```

I want to pass in function `on_resizestop_expression` addition parameters, how i can achieve it?

My function `on_resizestop_expression` looks like this:
```javascript
on_resizestop_expression(left, top, width, height, some, my, parameters) {
// ...
}
```

So, `left, top width, height` - i got, no problem, but i want to get `some, my, parameters` too in this function.

**Comment by mauricius** [comment]
Use an arrow function before calling your handler.
```
<vue-draggable-resizable @resizestop="(left, top, width, height) => resizeStop(left, top, width, height, 'some', 'my', 'parameters')">

on_resizestop_expression(left, top, width, height, some, my, parameters) {
// ...
}
```

**Comment by dikkini** [comment]
thanks! it works!
