### ISSUE TITLE
Any ways to copy or clone the element is about to drag?

### ISSUE THREAD

**Issue by sprklinginfo** [mauricius/vue-draggable-resizable#245]
one of the requirements of my project is to drag a copy of an element and drop it into another container. so for the same type of element, users can drag and drop multiple times. are there props or config for this? Many thanks.

**Comment by TitanFighter** [comment]
Just an idea - create 2 components with identical coordinates, so user can drag the top one. Also maybe you need [vue-smooth-dnd](https://github.com/kutlugsahin/vue-smooth-dnd) instead of vue-draggable-resizable

**Comment by mauricius** [comment]
@sprklinginfo yeah probably you're looking for a different library because VDR doesn't really meet your requirements.
