### ISSUE TITLE
Remove Dotted Line around the component

### ISSUE THREAD

**Issue by henriquegmatos** [mauricius/vue-draggable-resizable#258]
Hello Dear,

There is a way to remove or redefine to full-line the line around the component?

is it posible set a different style to this line?

thanks

**Comment by TitanFighter** [comment]
1. https://github.com/mauricius/vue-draggable-resizable#styling
2. https://github.com/mauricius/vue-draggable-resizable#classname
3. https://mauricius.github.io/vue-draggable-resizable/?path=/story/styling--style-component
