### ISSUE TITLE
Maintain aspect ratio on resizing?

### ISSUE THREAD

**Issue by runrog** [mauricius/vue-draggable-resizable#26]
Are there any plans to add this functionality anytime soon? Possibly as a prop boolean value or another common experience is when users hold the shift key on resize to maintain the ratio.

**Comment by mauricius** [comment]
Yes I'm planning to add this functionality, sometimes in the future. However I really cannot make estimates at this point.

**Comment by misaizdaleka** [comment]
+1

**Comment by terryw3316** [comment]
Any news on this feature?  This would be REALLY helpful :)

**Comment by fooness** [comment]
Think this feature is mandatory. Would love to see it being added, so we can use this great module.

**Comment by Siriki-Saikiran** [comment]
+1

**Comment by gazreyn** [comment]
Just giving my support on this feature

**Comment by jmatthiesen81** [comment]
#97 Maybe some of you guys wanna try my pull request?

**Comment by mauricius** [comment]
Aspect ratio functionality is available with the new major version on the dev branch. Right now it's in beta, but hopefully this will get released soon. It just need a little bit more of testing.

**Comment by websanova** [comment]
Will this get merged in soon? Waiting for this :P

**Comment by NotsayJustdo** [comment]
@mauricius  when aspect ratio get released? look forward to new features!

**Comment by TitanFighter** [comment]
Use v2 from dev branch.

`npm install https://github.com/mauricius/vue-draggable-resizable#develop --save`

Then in your `main.js`:
```
import VueDraggableResizable from 'vue-draggable-resizable/src/index'
import 'vue-draggable-resizable/src/components/vue-draggable-resizable.css'
Vue.component('vue-draggable-resizable', VueDraggableResizable)
```

[LockAspectRation](https://github.com/mauricius/vue-draggable-resizable/tree/develop#lockaspectratio)
