### ISSUE TITLE
Dynamically Adjust height to fit content. 

### ISSUE THREAD

**Issue by adamprocter** [mauricius/vue-draggable-resizable#277]
I would like to adjust the height of the draggable element as content expands dynamically in it. Setting css to min-height doesn’t help. I am assuming I need to update the height attribute with some JavaScript but wasn’t sure if this was already built in? Thanks

**Comment by TitanFighter** [comment]
Get height of content, then using `h` prop set height of draggable element.

Or like this: https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-auto-size

**Comment by adamprocter** [comment]
Thanks , Yes I am now re-setting the height based on content and drag box size now as the auto thing doesnt stay in place once you start moving and resizing manually, where as checking I can resize on drop

**Comment by adamprocter** [comment]
I wonder if there maybe a way to do this with the objects so they always respect the content https://dev.to/sammm/using-mutationobserver-and-resizeobserver-to-measure-a-changing-dom-element-in-vue-3jpd

**Comment by TitanFighter** [comment]
What **objects** do you mean?

**Comment by adamprocter** [comment]
I just mean the draggable objects

**Comment by TitanFighter** [comment]
> Thanks , Yes I am now re-setting the height based on content and drag box size now as the auto thing doesnt stay in place once you start moving and resizing manually, where as checking I can resize on drop

This is a bit mixed, so probably this is the reason I do not understand something. Does it mean that you change height but then if you drag or resize an object, the height is reset?

**Comment by adamprocter** [comment]
Sorry Im probably not being clear and I have a workround but see this video - the content on auto can still fall out of the container once resized even with Auto on https://www.loom.com/share/1cf3e4e149534daabdcd3e4f5ab606c4

**Comment by TitanFighter** [comment]
@adamprocter 

Here is the algorithm you need:
```
const textHeight = document.getElementsByClassName('draggable resizable vdr')[0].getElementsByTagName('p')[0].offsetHeight
```
Code is written for this example: https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-auto-size

Change width of container few times and after each change run the above code in console and you will catch the idea.
Then write a code where mix height of the container can not be less than `textHeight`.

**Comment by Adhders** [comment]
> I wonder if there maybe a way to do this with the objects so they always respect the content size https://dev.to/sammm/using-mutationobserver-and-resizeobserver-to-measure-a-changing-dom-element-in-vue-3jpd

you can try this way , changing  the content size through the item during dragging
@resizing="((x, y, width, height)=>{onResize(x, y, width, height,item)})"

**Comment by selfagency** [comment]
I'm doing more or less what @TitanFighter suggests but in a Vue way... 

```js
{
  data() {
    return {
      minHeight: 0,
    }
  },
  mounted() {
    this.$nextTick(() => {
      setTimeout(() => {
        this.minHeight = this.getHeight()
      }, 1000)
    })
  },
  methods: {
    getHeight() {
      const titleBar = this.$refs.titleBar?.$el
      const windowBody = this.$refs.windowBody

      return titleBar && windowBody
        ? titleBar.offsetHeight + windowBody.offsetHeight + 30
        : 0
    }
}
```

...and it appears that the properties aren't being updated reactively. As you can see here, the prop for 'min-height' isn't changing the data of 'minH' in the component. 

![CleanShot 2021-07-24 at 15 19 57](https://user-images.githubusercontent.com/2541728/126879192-8b39ecb7-9c16-4f5e-a652-dc579282210d.png)
