### ISSUE TITLE
Mouse events are prevented by draggable-resizable component

### ISSUE THREAD

**Issue by ktsn** [mauricius/vue-draggable-resizable#3]
Hi, I'm trying this component in my app. It's very nice 🙂 

One thing I encontered with this component is that it seems to capture all mousedown/move/up events and prevent other event listeners and native behaviors.
In my app, there are text input forms in draggable/resizable elements. And I also want to handle other drag events when the users drag out of draggable elements.

Here is the example for describing the above problem.
https://jsfiddle.net/kbhce3ht/

Is there any chance to satisfy such scenario somehow?

**Comment by mauricius** [comment]
Honestly I never tried the component with a form inside, such a particular use case 👍 

I just pushed the latest commit https://github.com/mauricius/vue-draggable-resizable/commit/910971c9eb02062f26bd11c1c392177ffc13c86a that should fix your issue. Just use version 1.0.2 and let me know.

**Comment by ktsn** [comment]
Thanks for the quick fix!
It works perfectly 👍
