### ISSUE TITLE
Why you add @media for class*="handle-" ？

### ISSUE THREAD

**Issue by JuneXuli** [mauricius/vue-draggable-resizable#307]
As title says, what do you mean to add this class?
Why do you think the class name containing "handle-" belonging to your own?
![image](https://user-images.githubusercontent.com/10702321/122772992-828e4f00-d2da-11eb-8f71-e790384e26a8.png)

**Comment by JuneXuli** [comment]
This caused my project error in some places where using "handle-"

**Comment by roy-yi** [comment]
I also met this problem.
Please fix it assp. Thx

**Comment by mauricius** [comment]
Why all this fuss? Just don't include the default CSS and use your own styles and classes.
