### ISSUE TITLE
How do I get the currently active instance

### ISSUE THREAD

**Issue by Zz-ZzzZ** [mauricius/vue-draggable-resizable#308]
I want to get the currently active instance when I call a method. Is there a good way?

**Comment by TitanFighter** [comment]
[This code](https://github.com/mauricius/vue-draggable-resizable/blob/master/stories/how-to/drag-multiple.js) may help (especially check `draggingElement` part).

**Comment by jinkunaier** [comment]
Yes,why not pass currently active instance as as parameter to activated、deactivated and other events ? so that we can get it.
