### ISSUE TITLE
Fix for css transform?

### ISSUE THREAD

**Issue by Zanzavar** [mauricius/vue-draggable-resizable#31]
First of all, this is a wonderful component and thank you so much for developing it. I have a small issue with it, when the parent element is modified by the css transform property the component does not move or resize according to the cursor position. Any idea how i could fix this? Thanks!

**Comment by mauricius** [comment]
Can you show me an example? The component registers the parent size when is mounted, so if you later try to change them through css, the calculations are not performed correctly.

**Comment by mauricius** [comment]
Closing. Let's track it on #91
