### ISSUE TITLE
辅助线功能怎么实现的

### ISSUE THREAD

**Issue by w958307583** [mauricius/vue-draggable-resizable#318]
大牛请教下 下载的demo没有辅助线功能呢
文档里也没有写是怎么实现的

**Comment by Hammer2014** [comment]
https://tingtas.com/vue-draggable-resizable-gorkys

**Comment by w958307583** [comment]
refLineParams 这个事件无法触发是怎么回事呢

**Comment by gorkys** [comment]
@w958307583 https://github.com/gorkys/vue-draggable-resizable-gorkys
npm install 这个修改库。
