### ISSUE TITLE
Bug: Resize on pre-activated component moves it out of bounds

### ISSUE THREAD

**Issue by shazow** [mauricius/vue-draggable-resizable#32]
How to reproduce:

1. Open https://mauricius.github.io/vue-draggable-resizable/
2. Scroll to `External activation`
3. Click [Activate Component]
4. Try resizing the top-right corner

Expected result: Position should stay the same, but size should change

Actual result: Position jumps to an out-of-bounds negative location, and size becomes undefined? Screenshot:

![image](https://user-images.githubusercontent.com/6292/31030918-0379d022-a525-11e7-95fa-c9bbf7150ece.png)

**Comment by shazow** [comment]
Sounds like a dupe of #30, feel free to close (though I'll let you do it in case the details/screenshot are useful).

**Comment by mauricius** [comment]
It should be fixed with https://github.com/mauricius/vue-draggable-resizable/commit/173c87b3a910b30998e9d9df91d8915f750ed107. Thanks for reporting!
