### ISSUE TITLE
It's not working with Vue 2.6.12 and ant design(1.7.2) table

### ISSUE THREAD

**Issue by yunusalgan** [mauricius/vue-draggable-resizable#328]
![Ekran görüntüsü 2021-12-20 100019](https://user-images.githubusercontent.com/16006905/146725479-08f9dcf6-66df-43be-9a53-8c11b3d7bbaa.png)

**Comment by mauricius** [comment]
It's not an issue of the component. You probably have to enclose `<th {...restProps}>{children}</th>` in round brackets.
