### ISSUE TITLE
 Moving an element only for a part of it.

### ISSUE THREAD

**Issue by YuriySimakov** [mauricius/vue-draggable-resizable#33]
Could you make the element move only for its part?
For example: moveheight = "10" - The item can be moved only if you take it over the top 10 picks.

**Comment by Lewik** [comment]
@YuriySimakov like window header?

**Comment by mauricius** [comment]
Implemented `dragHandle` and `dragCancel` props with https://github.com/mauricius/vue-draggable-resizable/commit/9809a4760d2b1cdc360b74309b0d21a162a31938
