### ISSUE TITLE
Cannot drag -x or -y from the parent

### ISSUE THREAD

**Issue by safrazik** [mauricius/vue-draggable-resizable#36]
E.g: if you look at the Basic Component example from https://mauricius.github.io/vue-draggable-resizable/ you can drag beyond the parent to right and bottom but not top or left beyond the borders. Is there a configuration I need to enable?

**Comment by alxpez** [comment]
I believe you could achieve that by modifying the `validator` function of `x` and `y` props:

From this:
```
validator: function (val) {
  return val >= 0
}
```
To this:
```
validator: function (val) {
  return typeof val === 'number'
}
```
Basically this would allow the VDR to move wherever, while still validating that a number is passed through. Maybe there's some more logic to it, since when the `parent` prop is `true`, the component needs to be kept within the parent boundaries.

**Comment by alxpez** [comment]
Actually on second thoughts, that may actually require some more tweaking, specially on the `handleMove` function, where the position of the element is calculated. Around these lines:

For x prop
```
if (this.elmX + dX < this.parentX) this.mouseOffX = (dX - (diffX = this.parentX - this.elmX))
else if (this.elmX + this.elmW + dX > this.parentW) this.mouseOffX = (dX - (diffX = this.parentW - this.elmX - this.elmW))
```
For y prop
```
if (this.elmY + dY < this.parentY) this.mouseOffY = (dY - (diffY = this.parentY - this.elmY))
else if (this.elmY + this.elmH + dY > this.parentH) this.mouseOffY = (dY - (diffY = this.parentH - this.elmY - this.elmH))
```

So it seems to have way more implications than expected at first glance. Ups!

**Comment by mauricius** [comment]
I'm currently rewriting the component (not from scratch, but close...), taking into accounts the small bugs that are still open and also adding a few improvements. I'm also planning to use the official [Vue testing library](https://github.com/vuejs/vue-test-utils).

The api will remain basically the same, therefore there will not be breaking changes. However this process could take some time to complete. I will take into account also this requirement.

**Comment by alxpez** [comment]
Cool, good news!

As a temporary fix, I think I found an easy way around this issue, without much refactoring, I can create a PR for the current version if you want.

It's basically a combination of modifying the validators, plus wrapping both the if/else conditions (that I mentioned above) on an `if (this.parent)`. This way I think nothing else gets affected.

Let me know

**Comment by safrazik** [comment]
Awesome work @mauricius and thanks for the fix @alxpez. I managed to have it without the fix but it will definitely be a needed feature. I will use the next version on my next project
