### ISSUE TITLE
Storybook: "Advanced -> Parent resize" has no effect

### ISSUE THREAD

**Issue by escapedcat** [mauricius/vue-draggable-resizable#380]
https://mauricius.github.io/vue-draggable-resizable/iframe.html?id=advanced--parent-resize
According to this story the component will resize. But resizing the window in any way doesn't change the component.

Is this story outdated? Am I doing something wrong? What should happen?

- Firefox 114.0.2 (64-bit) OSX
- Chrome Canary Version 117.0.5865.0 

Edit: 
~Also for this one the behaviour is unclear:~  
https://mauricius.github.io/vue-draggable-resizable/?path=/story/basic--basic-component-with-scale-prop
~The scale is being applied to the parent but then there's no change applied on the components?~
Edit:  
This only affects the *internal* movement I guess.  
"Parent resize" is still unclear to me.

**Comment by mauricius** [comment]
https://mauricius.github.io/vue-draggable-resizable/#/story/stories-advanced-parentresize-story-vue?variantId=_default

It's just to show that the component respects the parent if it gets resized.
