### ISSUE TITLE
Is it possible to make a child element the "drag trigger"?

### ISSUE THREAD

**Issue by liquidvisual** [mauricius/vue-draggable-resizable#39]
Hi there, thanks for writing such a great component! 

I'm coding a game that simulates an OS, and I'm trying to create app windows (think of a Finder window, or a browser) that are draggable by the toolbar only (a child div). How could I go about setting a drag "trigger" instead of the whole window enabling the drag behaviour?

**Comment by nikolay-borzov** [comment]
Similar to #33

**Comment by mauricius** [comment]
Yes I'm currently rewriting the component and this is one of the features that I'm planning to add. However I'm not sure when the new version will be released, so stay tuned!

**Comment by liquidvisual** [comment]
Sounds great. Love the component!

**Comment by mauricius** [comment]
You can use version 1.6.0 https://github.com/mauricius/vue-draggable-resizable/commit/9809a4760d2b1cdc360b74309b0d21a162a31938
