### ISSUE TITLE
opacity set to 0.6 when single click

### ISSUE THREAD

**Issue by renshuo** [mauricius/vue-draggable-resizable#4]
when single click the pane( not drag it), it turns to opacity=0.6 and then opacity=1. this isn't what I want. I think the opacity should be 0.6 only when it's dragging.

**Comment by mauricius** [comment]
I know, but internally the dragging starts when the user performs a mousedown event, even if you don't move the mouse. Turning opacity to 0.6 instead is something that I'd like to change in the future, probably by using different classes for dragging and resizing.

**Comment by mauricius** [comment]
I removed the opacity with the latest commit https://github.com/mauricius/vue-draggable-resizable/commit/3c605d255f329eb1259bc729557d0129ab720257. Now you can use the css classes `dragging` and `resizing` to set the desired styles.
