### ISSUE TITLE
Events dragstop and resizestop are not triggering.

### ISSUE THREAD

**Issue by kardeepak77** [mauricius/vue-draggable-resizable#400]
I am using latest bits.
Events dragstop and resizestop are not triggering.
@dragstop="console.log('Drag Stop')"
@resizestop="console.log('Resize Stop')"

Events dragging and resizing eventsare working fine.

 @dragging="console.log('Dragging)"
 @resizing="console.log('Resizing')"

**Comment by HLN177** [comment]
In the codebase, the events emitted are  "dragStop" and "resizeStop", and Vue provide an automatic case transformation for event names.

So try:
@drag-stop="console.log('Drag Stop')"
@resize-stop="console.log('Resize Stop')"

**Comment by HarryWuuuu** [comment]
I am curious why it worked in Vue2, Vue3 seems stricter than Vue2.

**Comment by HLN177** [comment]
Event in Vue2:
![image](https://github.com/mauricius/vue-draggable-resizable/assets/58175242/f46280d0-ee4c-4d0d-8407-f6cb2b2fd50d)

Event in Vue3:
![image](https://github.com/mauricius/vue-draggable-resizable/assets/58175242/1d4dc79a-be2a-4625-8f94-b88dbc69b9a1)

It seems Vue3 provided some  automatic case transformation feature to align with the nature of "props".

**Comment by kardeepak77** [comment]
Thank you @drag-stop and @resize-stop worked!

**Comment by kardeepak77** [comment]
Closing issue. 
To catch drag stop and resize stop event use following -
@drag-stop="console.log('Drag Stop')"
@resize-stop="console.log('Resize Stop')"

**Comment by HarryWuuuu** [comment]
> Event in Vue2: ![image](https://private-user-images.githubusercontent.com/58175242/300771629-f46280d0-ee4c-4d0d-8407-f6cb2b2fd50d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQ5MTcsIm5iZiI6MTcwNjcwNDYxNywicGF0aCI6Ii81ODE3NTI0Mi8zMDA3NzE2MjktZjQ2MjgwZDAtZWU0Yy00ZDBkLTg0MDctZjZjYjJiMmZkNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMzI0ZDJiMWUwNTU0YWFlZDdkMjJiNGExMjc2ODI0MWMwZjdlZTZhM2VmNzk0MmRhMmQ0NGViOWQxZWI4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSluAOZdCX0TDJuIgkg-3m-7sY95yCN3bovH0z1hqNM)
> 
> Event in Vue3: ![image](https://private-user-images.githubusercontent.com/58175242/300772178-1d4dc79a-be2a-4625-8f94-b88dbc69b9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQ5MTcsIm5iZiI6MTcwNjcwNDYxNywicGF0aCI6Ii81ODE3NTI0Mi8zMDA3NzIxNzgtMWQ0ZGM3OWEtYmUyYS00NjI1LThmOTQtYjg4ZGJjNjliOWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMzNmZWU5NjkyYjM5OGRlMTdjOTgwMTNjYWI1ODE3YTcyNTg0NmY4MzU3ZDc1NzYxZjQ5N2Q0Y2ZjZjJmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jr5-L9DAsfne5H5QXxA-bhyOEhV18rJ3DhF5Z7ZOKI)
> 
> It seems Vue3 provided some automatic case transformation feature to align with the nature of "props".

Actually, I still don't understand. 
As the documented illustrated, `v-on:dragStop `will become `v-on:dragstop` in Vue2 because DOM template automatically transforms it to lowercase. So, the `@dragstop` shouldn't work in Vue2 as Vue-Draggable-Resizable emits `dragStop` event which is camel case and dragstop doesn't match dragStop. However it actually works ok in Vue2. 
How to explain this one?

**Comment by HLN177** [comment]
> > Event in Vue2: ![image](https://private-user-images.githubusercontent.com/58175242/300771629-f46280d0-ee4c-4d0d-8407-f6cb2b2fd50d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQ5MTcsIm5iZiI6MTcwNjcwNDYxNywicGF0aCI6Ii81ODE3NTI0Mi8zMDA3NzE2MjktZjQ2MjgwZDAtZWU0Yy00ZDBkLTg0MDctZjZjYjJiMmZkNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMzI0ZDJiMWUwNTU0YWFlZDdkMjJiNGExMjc2ODI0MWMwZjdlZTZhM2VmNzk0MmRhMmQ0NGViOWQxZWI4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSluAOZdCX0TDJuIgkg-3m-7sY95yCN3bovH0z1hqNM)
> > Event in Vue3: ![image](https://private-user-images.githubusercontent.com/58175242/300772178-1d4dc79a-be2a-4625-8f94-b88dbc69b9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQ5MTcsIm5iZiI6MTcwNjcwNDYxNywicGF0aCI6Ii81ODE3NTI0Mi8zMDA3NzIxNzgtMWQ0ZGM3OWEtYmUyYS00NjI1LThmOTQtYjg4ZGJjNjliOWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMzNmZWU5NjkyYjM5OGRlMTdjOTgwMTNjYWI1ODE3YTcyNTg0NmY4MzU3ZDc1NzYxZjQ5N2Q0Y2ZjZjJmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jr5-L9DAsfne5H5QXxA-bhyOEhV18rJ3DhF5Z7ZOKI)
> > It seems Vue3 provided some automatic case transformation feature to align with the nature of "props".
> 
> Actually, I still don't understand. As the documentation illustrated, `v-on:dragStop `will become `v-on:dragstop` in Vue2 because DOM template automatically transforms it to lowercase. So, the `@dragstop` shouldn't work in Vue2 as Vue-Draggable-Resizable emits `dragStop` event which is camel case and `dragstop` doesn't match `dragStop`. However it actually works ok in Vue2. How to explain this one?

You are right and I am sure you understand the Vue2 case transformation very well.

Coz I have took a look into the commit history and found these two small changed.

On 03/01/2024
![image](https://github.com/mauricius/vue-draggable-resizable/assets/58175242/af96b677-1658-402c-b523-1f6042f36f62)

On 16/04/2023
![image](https://github.com/mauricius/vue-draggable-resizable/assets/58175242/aac5fffe-8eef-412c-a5df-9972d51f13a0)


So before 16/04/2023, when this project haven't immigrate to Vue3 , @dragstop worked fine all the way. : )

**Comment by HarryWuuuu** [comment]
> > > Event in Vue2: ![image](https://private-user-images.githubusercontent.com/58175242/300771629-f46280d0-ee4c-4d0d-8407-f6cb2b2fd50d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQ5MTcsIm5iZiI6MTcwNjcwNDYxNywicGF0aCI6Ii81ODE3NTI0Mi8zMDA3NzE2MjktZjQ2MjgwZDAtZWU0Yy00ZDBkLTg0MDctZjZjYjJiMmZkNTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwMzI0ZDJiMWUwNTU0YWFlZDdkMjJiNGExMjc2ODI0MWMwZjdlZTZhM2VmNzk0MmRhMmQ0NGViOWQxZWI4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kSluAOZdCX0TDJuIgkg-3m-7sY95yCN3bovH0z1hqNM)
> > > Event in Vue3: ![image](https://private-user-images.githubusercontent.com/58175242/300772178-1d4dc79a-be2a-4625-8f94-b88dbc69b9a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDQ5MTcsIm5iZiI6MTcwNjcwNDYxNywicGF0aCI6Ii81ODE3NTI0Mi8zMDA3NzIxNzgtMWQ0ZGM3OWEtYmUyYS00NjI1LThmOTQtYjg4ZGJjNjliOWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEyMzY1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMzNmZWU5NjkyYjM5OGRlMTdjOTgwMTNjYWI1ODE3YTcyNTg0NmY4MzU3ZDc1NzYxZjQ5N2Q0Y2ZjZjJmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6jr5-L9DAsfne5H5QXxA-bhyOEhV18rJ3DhF5Z7ZOKI)
> > > It seems Vue3 provided some automatic case transformation feature to align with the nature of "props".
> > 
> > 
> > Actually, I still don't understand. As the documentation illustrated, `v-on:dragStop `will become `v-on:dragstop` in Vue2 because DOM template automatically transforms it to lowercase. So, the `@dragstop` shouldn't work in Vue2 as Vue-Draggable-Resizable emits `dragStop` event which is camel case and `dragstop` doesn't match `dragStop`. However it actually works ok in Vue2. How to explain this one?
> 
> You are right and I am sure you understand the Vue2 case transformation very well.
> 
> Coz I have took a look into the commit history and found these two small changed.
> 
> On 03/01/2024 ![image](https://private-user-images.githubusercontent.com/58175242/301180095-af96b677-1658-402c-b523-1f6042f36f62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTA0MDEsIm5iZiI6MTcwNjc1MDEwMSwicGF0aCI6Ii81ODE3NTI0Mi8zMDExODAwOTUtYWY5NmI2NzctMTY1OC00MDJjLWI1MjMtMWY2MDQyZjM2ZjYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMWVmZjdlZDNlY2QzOWFmNDNiMzY3NDBiODUzYjUwMWIxMDljNTRiNmFkZTI0OGEyM2M0ZTAwYzdiYjA1YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.d4YNZUF05NGJeL-reRh9lAzCIZi-QygZSxmCrCOqYxw)
> 
> On 16/04/2023 ![image](https://private-user-images.githubusercontent.com/58175242/301179790-aac5fffe-8eef-412c-a5df-9972d51f13a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTA0MDEsIm5iZiI6MTcwNjc1MDEwMSwicGF0aCI6Ii81ODE3NTI0Mi8zMDExNzk3OTAtYWFjNWZmZmUtOGVlZi00MTJjLWE1ZGYtOTk3MmQ1MWYxM2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxMTUwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZDg4YWNiNTIyNzgwNzQ4ODlmMWU1ZWU2ZDI4NmRjYmU1N2I3M2UzYjE2ZDMyZWFmOTdiZGI3Y2IxYmExMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mzOW9gBqxif8X4eIsdvo8nsB4s26Q30PxrmzSESxvwM)
> 
> So before 16/04/2023, @dragstop worked fine all the way. : )

Not only in `vue-draggable-resizable`, in Vue2, any custom event with camel case name can be listened with camel case listener correctly. Not as that illustrated in Vue2 Doc. So wired.
