### ISSUE TITLE
[FEATURE] Prevent overlapping of elements

### ISSUE THREAD

**Issue by psychonetic** [mauricius/vue-draggable-resizable#45]
Hello, 

I want to build an event calender and was wondering if there is any way by default to disable overlapping of two elements?
So eg. in a calender if you have 2 events they shouldn't overlap visually. (because you can't be at two events at the same time)

Cheers.

**Comment by mauricius** [comment]
No, there is not. See https://github.com/mauricius/vue-draggable-resizable/issues/18 for the reasons.

I'm also sure that for an event calendar there are more suitable options. You can use, for example, the wonderful https://fullcalendar.io/
