### ISSUE TITLE
[feature request]allow auto for w,h,minw,minh when resizable is false

### ISSUE THREAD

**Issue by hkuclion** [mauricius/vue-draggable-resizable#46]
When sometimes I want to only drag something, the default value of w,h,minw,minh affect me a lot,
for that I need to calculate these where it's almost impossible.
So could these values be a string "auto" which means don't touch original value if not resizable, or calculate these values automatically when dom is ready?

**Comment by mauricius** [comment]
Currently this feature is not available. I'm currently rewriting the component with new functionalities, including this one as well.

**Comment by rjhall90** [comment]
Is this still planned for the roadmap? It would be really useful to be able to initially size the object automatically based on its children.

**Comment by mauricius** [comment]
A little bit late, but see #220
