### ISSUE TITLE
Props will support conflict detection? 

### ISSUE THREAD

**Issue by gorkys** [mauricius/vue-draggable-resizable#47]
Props will support conflict detection? Can not overlap each other!
Forgive me for my poor English~

**Comment by gorkys** [comment]
When the props overlap, the active should return to the previous position.

**Comment by gorkys** [comment]
Under the test version of the branch, add their own conflict detection, a little bug, but finally able to run.

**Comment by mauricius** [comment]
Closing! See #18 and #109
