### ISSUE TITLE
how to solve the problem of non-stick when parent dom has attr transform:scale(0.5)

### ISSUE THREAD

**Issue by yj7810520113** [mauricius/vue-draggable-resizable#51]
such as:
```
<div style="transform:scale(0.5)">
    <vue-draggable-resizable></vue-draggable-resizable>
    <vue-draggable-resizable></vue-draggable-resizable>
    <vue-draggable-resizable></vue-draggable-resizable>
</div>
```
when i drag or resize the vue-draggable-resizable,it's can't follow my cursor. Thank you.

**Comment by mauricius** [comment]
Perhaps I'm missing something, but I really think that this behavior is correct. If the mouse moves 1 pixel, the change is reflected only by one half on the component, since you are using scale(0.5). I guess that the component doesn't play nicely with css transforms.

**Comment by yj7810520113** [comment]
@mauricius 
My solution：
such as 
transform:scale(0.5); let zoom=0.5
```
handleMove:function(){
//....some code
        let dX = diffX/this.getZoom
        let dY = diffY/this.getZoom
this.elmY += diffY/this.getZoom
this.elmH -= diffY/this.getZoom
this.elmX += diffX/this.getZoom
this.elmW -= diffX/this.getZoom
//...some code
}
```
If the mouse moves 1 pixel,the change is reflected  by 2 pixel on the component, so the component can play nicely with css transforms(scale(0.5))
Thanks！
