### ISSUE TITLE
Is it possible to have some sort of overlap detection ?

### ISSUE THREAD

**Issue by minedun6** [mauricius/vue-draggable-resizable#56]
I would like to know if there is some sort of way to detect element overlapping ?
I'm building a dynamic tile grid ui with jquery-ui-draggable/resizable, problem is that it's too much code to maintain and it's ui reliant in most cases using this approach
```
$('.tile.ui-resizable:not(.tile.ui-resizing)').each(function ( {
    // logic to check the current tile against all the existing tiles
}))
```

And yes in this instance I really need collision detection.

**Comment by gorkys** [comment]
I have a modified version here that can do simple collision detection.

**Comment by minedun6** [comment]
@gorkys and how is it possible to check for collision detection ?
I mean in a way that the drag/resize doesn't overlap with other elements.
Maybe add a prop "loose" to ignore collision or enable it ?
Wouldn't that be better ?

**Comment by gorkys** [comment]
Yes, I added a prop, but it was not that perfect。

**Comment by robodude** [comment]
I think it would be great if in addition to checking for overlaps, maybe you can prevent draggable elements from overlapping all together.

**Comment by robodude** [comment]
@gorkys Where is the code that checks collision detection? How can I test out your changes?

**Comment by gorkys** [comment]
@robodude [vue-draggable-resizable.vue](https://github.com/gorkys/realboxVue/blob/master/src/components/common/vue-draggable-resizable.vue)
You can copy it here. The project README.md on the prop there is an explanation, in the third. ps: the comment inside is Chinese.

**Comment by gorkys** [comment]
@robodude If you have any questions can send me an email, email: king@tingtas.com

**Comment by gorkys** [comment]
@robodude The current test, moving the two regions will be 1px interval, if you are interested, maybe we can discuss, how to make them fully fit.

**Comment by mauricius** [comment]
Closing! See #18 and #109 for explanation.
