### ISSUE TITLE
Dragging/Resizing element adds width

### ISSUE THREAD

**Issue by minedun6** [mauricius/vue-draggable-resizable#57]
This is an odd behaviour, I've set the :w="128" :h="128" but oddly I found that after dragging/resizing an element, the width/height of the element becomes 132/132 respectivly.

Is it a normal behavour or what ? and if it is, how can I prevent such behaviour.

A good library that provides robust ui handling.

**Comment by gorkys** [comment]
I have a modified version here that can do simple collision detection.

**Comment by minedun6** [comment]
Same as #58.
