### ISSUE TITLE
very good just on mobile doesnt resize

### ISSUE THREAD

**Issue by 33sKamal** [mauricius/vue-draggable-resizable#6]
i like this one it does a lot,
thanks
but i try to use it on mobile and it does not work
any idea

**Comment by mauricius** [comment]
The component just doesn't support mobile devices. Unfortunately it introduces a lot of complexity. I'm willing to add support for it in a future release, but at this moment I don't have the required knowledge to make it work.

**Comment by 33sKamal** [comment]
good lock & thanks

**Comment by pixelspark** [comment]
@mauricius first just wanted to say your library is great! second, I'd also love it to work on mobile. 

Could you elaborate on where the complexity is? If I understand correctly you'd need to deal with touch events (ontouchstart/move/end) in addition to mouse events. Otherwise logic should be similar, right?

**Comment by mesqueeb** [comment]
@mauricius I agree with @pixelspark. I'm currently in the market for a library that supports resize and drag on a div on mobile. Like google calendar events.
I'd be willing to pay even! Are you planning on this soon? Can we help?

**Comment by mauricius** [comment]
@pixelspark Sorry for the delay! I've been pretty busy in the last few weeks.

You are right, the logic is similar, however I encountered a few difficulties dealing with multitouch events. I'm currently trying to fix bugs related to grid, so I'm not looking into it in the near future. Feel free to submit a PR if you sort it out. Same for you @mesqueeb Thanks

**Comment by ojczeo** [comment]
PR with mobile support waiting for tests and merge :)
https://github.com/mauricius/vue-draggable-resizable/pull/77
