### ISSUE TITLE
'drag-handle' param not support Edge Bowser

### ISSUE THREAD

**Issue by ghost** [mauricius/vue-draggable-resizable#62]
use prop drag-handle
Edge: Object doesn't support property or method 'matches'

**Comment by liquidvisual** [comment]
It looks like the dragging doesn't work at all in Edge, with a drag-handle or not. I can't seem to click on anything inside the draggable too, so no nested elements are receiving any events - strange.

**Comment by hwp82316** [comment]
@liquidvisual 

edit dom.js **node.matches**

`.matches = function(_elm, _selector) { 
return (_elm.matches || _elm.matchesSelector || _elm.msMatchesSelector || _elm.mozMatchesSelector || _elm.webkitMatchesSelector || _elm.oMatchesSelector).call(_elm, _selector);
}`
