### ISSUE TITLE
maxw and maxh props

### ISSUE THREAD

**Issue by DeltaEvo** [mauricius/vue-draggable-resizable#76]
:smile:

**Comment by Markeldo** [comment]
need it so much

**Comment by TitanFighter** [comment]
Current state, according to the [ROADMAP](https://github.com/mauricius/vue-draggable-resizable#roadmap) -> `maxWidth and maxHeight props (#76) - In progress`.

I hope soon we will see v2 in production :)

**Comment by mauricius** [comment]
https://github.com/mauricius/vue-draggable-resizable#maxwidth and https://github.com/mauricius/vue-draggable-resizable#maxheight
