### ISSUE TITLE
Deleting index of array

### ISSUE THREAD

**Issue by CrazyAlien1** [mauricius/vue-draggable-resizable#78]
Hi there,

I'm using an array to display charts, 
<vue-draggable-resizable  v-for="(component,keyComp) in dropedItems" ...>
I'm experiencing an odd behaviour once I remove an element from the array.

I'm adding the components as I drop them (create a new object in the array).
If I do this to 2 components A and B and added to the array by that order A first and B second.
Then If I delete A the B component will assume A's position, but if I delete B instead of A, A continues in the same position.

**Comment by Saraad** [comment]
Same problem for me...

**Comment by imadentive** [comment]
I have this problem, too

**Comment by mauricius** [comment]
Can you post some code so I can take a look?

**Comment by yunlonglee** [comment]
same problem here. Did you fixed it?

**Comment by CrazyAlien1** [comment]
I'm really sry but I haven't had the time to create a small sample for mauricius. I'd apreeciate if someone else could post one.

**Comment by yunlonglee** [comment]
`<template lang="pug">
 template(v-for="(data,index) in dataList")
                        vue-draggable-resizable(:parent="true", :w='data.width', :h='data.height', :y='data.top', :x="data.left" @resizestop='(x,y,w,h) => updateSize(data, x, y, w, h)', @dragstop='(x,y) => updatePosition(data, x, y)')
                            i.fa.fa-trash(@click="deleteItem(data, index)")

</template>`

`<script>
import VueDraggableResizable from 'vue-draggable-resizable'

export default {
    data () {
        return {
            dataList: [
                   {
                     height:123,
                     left:14,
                     top:9,
                     width:324
                   },
                  {
                     height:191,
                     left:3,
                     top:166,
                     width:215
                   }
            ],
        }
    },
    methods: {
        deleteItem (data, index) {
            this.dataList.splice(index,1)
        }
    }
}
</script>`

**Comment by mauricius** [comment]
See https://github.com/mauricius/vue-draggable-resizable/issues/84#issuecomment-390474756
