### ISSUE TITLE
add rotation feature 

### ISSUE THREAD

**Issue by ejlungay** [mauricius/vue-draggable-resizable#79]
It is working well until I add a function to rotate a single **vue-draggable-resizable** item. When it is rotated, the resize function is acting unnaturally. 
Attached below is the reproduction steps:
![reproduction-example](https://user-images.githubusercontent.com/15153018/38343177-f8148316-38b4-11e8-9e3f-cb5623ed160d.gif)

this is the code for rotating the item
`var center_x = offset.left + elem.offsetWidth  / 2;
        var center_y = offset.top + elem.offsetHeight / 2;
        var mouse_x = evt.clientX;
        var mouse_y = evt.clientY;
        var radians = Math.atan2(mouse_x - center_x, mouse_y - center_y);
        var degree = radians * (180 / Math.PI) * -1 + 180;
        console.log('degree', degree);
        elem.style.cssText += "-moz-transform: rotate(" + degree + "deg)"; // firefox
        elem.style.cssText += "-webkit-transform: rotate(" + degree + "deg)"; // chome
        elem.style.cssText += "-o-transform: rotate(" + degree + "deg)"; // safari
        elem.style.cssText += "-ms-transform: rotate(" + degree + "deg)"; // edge/ie`

**Comment by NastuzziSamy** [comment]
Hey @ejlungay , how did you manage to do that ?

Thanks

**Comment by shiyuegongsui** [comment]
Have you solved it?  I have the same question ~!

**Comment by mauricius** [comment]
This project will unlikely support rotation in the future. For anyone looking for an awesome alternative check out the [Movable](https://daybrush.com/moveable/release/latest/doc/index.html) package.
