### ISSUE TITLE
Deleting an array of problems

### ISSUE THREAD

**Issue by messieurspeng** [mauricius/vue-draggable-resizable#84]
When I delete an item of the array, the array of the next item will inherit the position of the deleted item.

**Comment by messieurspeng** [comment]
Delete array update location failed

**Comment by joshi-mehul** [comment]
@messieurspeng please provide an example with screenshot or code.

**Comment by messieurspeng** [comment]
After I clicked this method, the dragList array was deleted, but the location was disturbed when the view was updated.
`detele(index){
     this.dragList.splice(index , 1)
 }`
array ：
`dragList : [
					{ left : 50 , top : 50 , width : 120 , height : 120 , fontSize : '12px' , name : 'a'},
					{ left : 50 , top : 200 , width : 100 , height : 100, fontSize : '20px' ,  name : 'b'}
				],`

**Comment by messieurspeng** [comment]
The array information is correct after deleting, but there will be problems in view updating.

**Comment by yunlonglee** [comment]
same problem here, did you fixed?

**Comment by mauricius** [comment]
I think I know what's wrong in this case. You have to provide the `key` attribute to each item, otherwise Vue doesn't know how to reorder existing elements.

https://vuejs.org/v2/guide/list.html#key

The following example works correctly:

```
<VueDraggableResizable v-for="(component, index) in components" :key="component.id" :x="component.x" :y="component.y" :w="component.w" :h="component.h">
    <p>{{ component.text }}</p>
    <button @click="deleteMe(index)">Delete me</button>
</VueDraggableResizable>

<script>
export default {
  data: function () {
    return {
      components: [
        {id: 1, x: 50, y: 50, w: 100, h: 100, text: 'Component 1'},
        {id: 2, x: 150, y: 150, w: 100, h: 100, text: 'Component 2'},
        {id: 3, x: 250, y: 250, w: 100, h: 100, text: 'Component 3'}
      ]
    }
  },
  methods: {
    deleteMe (index) {
      this.components.splice(index, 1)
    }
  }
}
</script>
```
