### ISSUE TITLE
I can't make the width smaller than 50px

### ISSUE THREAD

**Issue by trufa** [mauricius/vue-draggable-resizable#85]
I made a live demo:

https://jsfiddle.net/zkw4f8o4/

As you will be able to see, I can set the `w` prop with success above 50px but not below.

Is there anyway around this?

Thanks in advance!

**Comment by alxpez** [comment]
You have the props `:minw` and `:minh`, to setup the he minWidth and minHeight attributes.
https://github.com/mauricius/vue-draggable-resizable#minw
