### ISSUE TITLE
How can I keep the active class when I click the outside component?

### ISSUE THREAD

**Issue by Kennersky** [mauricius/vue-draggable-resizable#88]
I don't want the plugin remove the 'active' class automatic. How should I do?

**Comment by mauricius** [comment]
Right now this is not possible, but you can take a look at the new major version on the develop branch which has a prop that prevents the deactivation of the component. Hopefully soon this will replace version 1.

**Comment by javalink** [comment]
Hello, has this problem been solved? If you solve it, please tell me how to do it.

**Comment by gorkys** [comment]
@javalink you see https://github.com/mauricius/vue-draggable-resizable/issues/18
