### ISSUE TITLE
Option to be adaptable to content not fixed size

### ISSUE THREAD

**Issue by kenyk7** [mauricius/vue-draggable-resizable#9]

**Comment by mauricius** [comment]
Can you provide an example or a use case? I'm not sure I understand your request.

**Comment by kenyk7** [comment]
For default size to content: example.
https://www.webpackbin.com/bins/-KpGxXY8WCacQPJkukcs

**Comment by kenyk7** [comment]
For example if resizable prop is false, the width and height to be in automatic.

**Comment by mauricius** [comment]
Theoretically would be possible to achieve what you're saying, however this introduces more complexity when the component is contrained in parent. If the size of the component exceeds the bounds, the dragging of the element becomes unmanageable.

I prefer to have a component that does a few things, but does them well.
